// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

public interface CoinInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tradeflux.CoinInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>string base_asset = 2;</code>
   * @return The baseAsset.
   */
  java.lang.String getBaseAsset();
  /**
   * <code>string base_asset = 2;</code>
   * @return The bytes for baseAsset.
   */
  com.google.protobuf.ByteString
      getBaseAssetBytes();

  /**
   * <code>string quote_asset = 3;</code>
   * @return The quoteAsset.
   */
  java.lang.String getQuoteAsset();
  /**
   * <code>string quote_asset = 3;</code>
   * @return The bytes for quoteAsset.
   */
  com.google.protobuf.ByteString
      getQuoteAssetBytes();

  /**
   * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
   * @return A list containing the orderTypes.
   */
  java.util.List<com.tradeflux.grpc.OrderTypes> getOrderTypesList();
  /**
   * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
   * @return The count of orderTypes.
   */
  int getOrderTypesCount();
  /**
   * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
   * @param index The index of the element to return.
   * @return The orderTypes at the given index.
   */
  com.tradeflux.grpc.OrderTypes getOrderTypes(int index);
  /**
   * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
   * @return A list containing the enum numeric values on the wire for orderTypes.
   */
  java.util.List<java.lang.Integer>
  getOrderTypesValueList();
  /**
   * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of orderTypes at the given index.
   */
  int getOrderTypesValue(int index);

  /**
   * <code>bool is_margin_trading_allowed = 5;</code>
   * @return The isMarginTradingAllowed.
   */
  boolean getIsMarginTradingAllowed();
}
