// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

/**
 * Protobuf type {@code tradeflux.CoinPrice}
 */
public final class CoinPrice extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tradeflux.CoinPrice)
    CoinPriceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CoinPrice.newBuilder() to construct.
  private CoinPrice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CoinPrice() {
    symbol_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CoinPrice();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CoinPrice(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            symbol_ = s;
            break;
          }
          case 17: {

            price_ = input.readDouble();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000001;
            averagePriceIntervalMins_ = input.readInt32();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000002;
            lastTradeTime_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_CoinPrice_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_CoinPrice_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tradeflux.grpc.CoinPrice.class, com.tradeflux.grpc.CoinPrice.Builder.class);
  }

  private int bitField0_;
  public static final int SYMBOL_FIELD_NUMBER = 1;
  private volatile java.lang.Object symbol_;
  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICE_FIELD_NUMBER = 2;
  private double price_;
  /**
   * <code>double price = 2;</code>
   * @return The price.
   */
  @java.lang.Override
  public double getPrice() {
    return price_;
  }

  public static final int AVERAGE_PRICE_INTERVAL_MINS_FIELD_NUMBER = 3;
  private int averagePriceIntervalMins_;
  /**
   * <code>int32 average_price_interval_mins = 3;</code>
   * @return Whether the averagePriceIntervalMins field is set.
   */
  @java.lang.Override
  public boolean hasAveragePriceIntervalMins() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>int32 average_price_interval_mins = 3;</code>
   * @return The averagePriceIntervalMins.
   */
  @java.lang.Override
  public int getAveragePriceIntervalMins() {
    return averagePriceIntervalMins_;
  }

  public static final int LAST_TRADE_TIME_FIELD_NUMBER = 4;
  private long lastTradeTime_;
  /**
   * <code>int64 last_trade_time = 4;</code>
   * @return Whether the lastTradeTime field is set.
   */
  @java.lang.Override
  public boolean hasLastTradeTime() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>int64 last_trade_time = 4;</code>
   * @return The lastTradeTime.
   */
  @java.lang.Override
  public long getLastTradeTime() {
    return lastTradeTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSymbolBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, symbol_);
    }
    if (price_ != 0D) {
      output.writeDouble(2, price_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(3, averagePriceIntervalMins_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(4, lastTradeTime_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSymbolBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, symbol_);
    }
    if (price_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, price_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, averagePriceIntervalMins_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, lastTradeTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tradeflux.grpc.CoinPrice)) {
      return super.equals(obj);
    }
    com.tradeflux.grpc.CoinPrice other = (com.tradeflux.grpc.CoinPrice) obj;

    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (java.lang.Double.doubleToLongBits(getPrice())
        != java.lang.Double.doubleToLongBits(
            other.getPrice())) return false;
    if (hasAveragePriceIntervalMins() != other.hasAveragePriceIntervalMins()) return false;
    if (hasAveragePriceIntervalMins()) {
      if (getAveragePriceIntervalMins()
          != other.getAveragePriceIntervalMins()) return false;
    }
    if (hasLastTradeTime() != other.hasLastTradeTime()) return false;
    if (hasLastTradeTime()) {
      if (getLastTradeTime()
          != other.getLastTradeTime()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrice()));
    if (hasAveragePriceIntervalMins()) {
      hash = (37 * hash) + AVERAGE_PRICE_INTERVAL_MINS_FIELD_NUMBER;
      hash = (53 * hash) + getAveragePriceIntervalMins();
    }
    if (hasLastTradeTime()) {
      hash = (37 * hash) + LAST_TRADE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastTradeTime());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tradeflux.grpc.CoinPrice parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.CoinPrice parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.CoinPrice parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.CoinPrice parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.CoinPrice parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.CoinPrice parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.CoinPrice parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.CoinPrice parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tradeflux.grpc.CoinPrice parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.CoinPrice parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tradeflux.grpc.CoinPrice parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.CoinPrice parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tradeflux.grpc.CoinPrice prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tradeflux.CoinPrice}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tradeflux.CoinPrice)
      com.tradeflux.grpc.CoinPriceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_CoinPrice_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_CoinPrice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tradeflux.grpc.CoinPrice.class, com.tradeflux.grpc.CoinPrice.Builder.class);
    }

    // Construct using com.tradeflux.grpc.CoinPrice.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      symbol_ = "";

      price_ = 0D;

      averagePriceIntervalMins_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      lastTradeTime_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_CoinPrice_descriptor;
    }

    @java.lang.Override
    public com.tradeflux.grpc.CoinPrice getDefaultInstanceForType() {
      return com.tradeflux.grpc.CoinPrice.getDefaultInstance();
    }

    @java.lang.Override
    public com.tradeflux.grpc.CoinPrice build() {
      com.tradeflux.grpc.CoinPrice result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tradeflux.grpc.CoinPrice buildPartial() {
      com.tradeflux.grpc.CoinPrice result = new com.tradeflux.grpc.CoinPrice(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.symbol_ = symbol_;
      result.price_ = price_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.averagePriceIntervalMins_ = averagePriceIntervalMins_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.lastTradeTime_ = lastTradeTime_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tradeflux.grpc.CoinPrice) {
        return mergeFrom((com.tradeflux.grpc.CoinPrice)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tradeflux.grpc.CoinPrice other) {
      if (other == com.tradeflux.grpc.CoinPrice.getDefaultInstance()) return this;
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        onChanged();
      }
      if (other.getPrice() != 0D) {
        setPrice(other.getPrice());
      }
      if (other.hasAveragePriceIntervalMins()) {
        setAveragePriceIntervalMins(other.getAveragePriceIntervalMins());
      }
      if (other.hasLastTradeTime()) {
        setLastTradeTime(other.getLastTradeTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tradeflux.grpc.CoinPrice parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tradeflux.grpc.CoinPrice) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object symbol_ = "";
    /**
     * <code>string symbol = 1;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string symbol = 1;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      symbol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      
      symbol_ = getDefaultInstance().getSymbol();
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 1;</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      symbol_ = value;
      onChanged();
      return this;
    }

    private double price_ ;
    /**
     * <code>double price = 2;</code>
     * @return The price.
     */
    @java.lang.Override
    public double getPrice() {
      return price_;
    }
    /**
     * <code>double price = 2;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(double value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double price = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      
      price_ = 0D;
      onChanged();
      return this;
    }

    private int averagePriceIntervalMins_ ;
    /**
     * <code>int32 average_price_interval_mins = 3;</code>
     * @return Whether the averagePriceIntervalMins field is set.
     */
    @java.lang.Override
    public boolean hasAveragePriceIntervalMins() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>int32 average_price_interval_mins = 3;</code>
     * @return The averagePriceIntervalMins.
     */
    @java.lang.Override
    public int getAveragePriceIntervalMins() {
      return averagePriceIntervalMins_;
    }
    /**
     * <code>int32 average_price_interval_mins = 3;</code>
     * @param value The averagePriceIntervalMins to set.
     * @return This builder for chaining.
     */
    public Builder setAveragePriceIntervalMins(int value) {
      bitField0_ |= 0x00000001;
      averagePriceIntervalMins_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 average_price_interval_mins = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAveragePriceIntervalMins() {
      bitField0_ = (bitField0_ & ~0x00000001);
      averagePriceIntervalMins_ = 0;
      onChanged();
      return this;
    }

    private long lastTradeTime_ ;
    /**
     * <code>int64 last_trade_time = 4;</code>
     * @return Whether the lastTradeTime field is set.
     */
    @java.lang.Override
    public boolean hasLastTradeTime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>int64 last_trade_time = 4;</code>
     * @return The lastTradeTime.
     */
    @java.lang.Override
    public long getLastTradeTime() {
      return lastTradeTime_;
    }
    /**
     * <code>int64 last_trade_time = 4;</code>
     * @param value The lastTradeTime to set.
     * @return This builder for chaining.
     */
    public Builder setLastTradeTime(long value) {
      bitField0_ |= 0x00000002;
      lastTradeTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 last_trade_time = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastTradeTime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      lastTradeTime_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tradeflux.CoinPrice)
  }

  // @@protoc_insertion_point(class_scope:tradeflux.CoinPrice)
  private static final com.tradeflux.grpc.CoinPrice DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tradeflux.grpc.CoinPrice();
  }

  public static com.tradeflux.grpc.CoinPrice getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CoinPrice>
      PARSER = new com.google.protobuf.AbstractParser<CoinPrice>() {
    @java.lang.Override
    public CoinPrice parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CoinPrice(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CoinPrice> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CoinPrice> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tradeflux.grpc.CoinPrice getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

