// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

/**
 * Protobuf type {@code tradeflux.CoinInfo}
 */
public final class CoinInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tradeflux.CoinInfo)
    CoinInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CoinInfo.newBuilder() to construct.
  private CoinInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CoinInfo() {
    symbol_ = "";
    baseAsset_ = "";
    quoteAsset_ = "";
    orderTypes_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CoinInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CoinInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            symbol_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            baseAsset_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            quoteAsset_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              orderTypes_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            orderTypes_.add(rawValue);
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int oldLimit = input.pushLimit(length);
            while(input.getBytesUntilLimit() > 0) {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                orderTypes_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              orderTypes_.add(rawValue);
            }
            input.popLimit(oldLimit);
            break;
          }
          case 40: {

            isMarginTradingAllowed_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        orderTypes_ = java.util.Collections.unmodifiableList(orderTypes_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_CoinInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_CoinInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tradeflux.grpc.CoinInfo.class, com.tradeflux.grpc.CoinInfo.Builder.class);
  }

  public static final int SYMBOL_FIELD_NUMBER = 1;
  private volatile java.lang.Object symbol_;
  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BASE_ASSET_FIELD_NUMBER = 2;
  private volatile java.lang.Object baseAsset_;
  /**
   * <code>string base_asset = 2;</code>
   * @return The baseAsset.
   */
  @java.lang.Override
  public java.lang.String getBaseAsset() {
    java.lang.Object ref = baseAsset_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      baseAsset_ = s;
      return s;
    }
  }
  /**
   * <code>string base_asset = 2;</code>
   * @return The bytes for baseAsset.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBaseAssetBytes() {
    java.lang.Object ref = baseAsset_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      baseAsset_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUOTE_ASSET_FIELD_NUMBER = 3;
  private volatile java.lang.Object quoteAsset_;
  /**
   * <code>string quote_asset = 3;</code>
   * @return The quoteAsset.
   */
  @java.lang.Override
  public java.lang.String getQuoteAsset() {
    java.lang.Object ref = quoteAsset_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      quoteAsset_ = s;
      return s;
    }
  }
  /**
   * <code>string quote_asset = 3;</code>
   * @return The bytes for quoteAsset.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQuoteAssetBytes() {
    java.lang.Object ref = quoteAsset_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      quoteAsset_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORDER_TYPES_FIELD_NUMBER = 4;
  private java.util.List<java.lang.Integer> orderTypes_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, com.tradeflux.grpc.OrderTypes> orderTypes_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, com.tradeflux.grpc.OrderTypes>() {
            public com.tradeflux.grpc.OrderTypes convert(java.lang.Integer from) {
              @SuppressWarnings("deprecation")
              com.tradeflux.grpc.OrderTypes result = com.tradeflux.grpc.OrderTypes.valueOf(from);
              return result == null ? com.tradeflux.grpc.OrderTypes.UNRECOGNIZED : result;
            }
          };
  /**
   * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
   * @return A list containing the orderTypes.
   */
  @java.lang.Override
  public java.util.List<com.tradeflux.grpc.OrderTypes> getOrderTypesList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, com.tradeflux.grpc.OrderTypes>(orderTypes_, orderTypes_converter_);
  }
  /**
   * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
   * @return The count of orderTypes.
   */
  @java.lang.Override
  public int getOrderTypesCount() {
    return orderTypes_.size();
  }
  /**
   * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
   * @param index The index of the element to return.
   * @return The orderTypes at the given index.
   */
  @java.lang.Override
  public com.tradeflux.grpc.OrderTypes getOrderTypes(int index) {
    return orderTypes_converter_.convert(orderTypes_.get(index));
  }
  /**
   * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
   * @return A list containing the enum numeric values on the wire for orderTypes.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
  getOrderTypesValueList() {
    return orderTypes_;
  }
  /**
   * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of orderTypes at the given index.
   */
  @java.lang.Override
  public int getOrderTypesValue(int index) {
    return orderTypes_.get(index);
  }
  private int orderTypesMemoizedSerializedSize;

  public static final int IS_MARGIN_TRADING_ALLOWED_FIELD_NUMBER = 5;
  private boolean isMarginTradingAllowed_;
  /**
   * <code>bool is_margin_trading_allowed = 5;</code>
   * @return The isMarginTradingAllowed.
   */
  @java.lang.Override
  public boolean getIsMarginTradingAllowed() {
    return isMarginTradingAllowed_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getSymbolBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, symbol_);
    }
    if (!getBaseAssetBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, baseAsset_);
    }
    if (!getQuoteAssetBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, quoteAsset_);
    }
    if (getOrderTypesList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(orderTypesMemoizedSerializedSize);
    }
    for (int i = 0; i < orderTypes_.size(); i++) {
      output.writeEnumNoTag(orderTypes_.get(i));
    }
    if (isMarginTradingAllowed_ != false) {
      output.writeBool(5, isMarginTradingAllowed_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSymbolBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, symbol_);
    }
    if (!getBaseAssetBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, baseAsset_);
    }
    if (!getQuoteAssetBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, quoteAsset_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < orderTypes_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(orderTypes_.get(i));
      }
      size += dataSize;
      if (!getOrderTypesList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }orderTypesMemoizedSerializedSize = dataSize;
    }
    if (isMarginTradingAllowed_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isMarginTradingAllowed_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tradeflux.grpc.CoinInfo)) {
      return super.equals(obj);
    }
    com.tradeflux.grpc.CoinInfo other = (com.tradeflux.grpc.CoinInfo) obj;

    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (!getBaseAsset()
        .equals(other.getBaseAsset())) return false;
    if (!getQuoteAsset()
        .equals(other.getQuoteAsset())) return false;
    if (!orderTypes_.equals(other.orderTypes_)) return false;
    if (getIsMarginTradingAllowed()
        != other.getIsMarginTradingAllowed()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    hash = (37 * hash) + BASE_ASSET_FIELD_NUMBER;
    hash = (53 * hash) + getBaseAsset().hashCode();
    hash = (37 * hash) + QUOTE_ASSET_FIELD_NUMBER;
    hash = (53 * hash) + getQuoteAsset().hashCode();
    if (getOrderTypesCount() > 0) {
      hash = (37 * hash) + ORDER_TYPES_FIELD_NUMBER;
      hash = (53 * hash) + orderTypes_.hashCode();
    }
    hash = (37 * hash) + IS_MARGIN_TRADING_ALLOWED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsMarginTradingAllowed());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tradeflux.grpc.CoinInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.CoinInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.CoinInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.CoinInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.CoinInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.CoinInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.CoinInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.CoinInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tradeflux.grpc.CoinInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.CoinInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tradeflux.grpc.CoinInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.CoinInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tradeflux.grpc.CoinInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tradeflux.CoinInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tradeflux.CoinInfo)
      com.tradeflux.grpc.CoinInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_CoinInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_CoinInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tradeflux.grpc.CoinInfo.class, com.tradeflux.grpc.CoinInfo.Builder.class);
    }

    // Construct using com.tradeflux.grpc.CoinInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      symbol_ = "";

      baseAsset_ = "";

      quoteAsset_ = "";

      orderTypes_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      isMarginTradingAllowed_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_CoinInfo_descriptor;
    }

    @java.lang.Override
    public com.tradeflux.grpc.CoinInfo getDefaultInstanceForType() {
      return com.tradeflux.grpc.CoinInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.tradeflux.grpc.CoinInfo build() {
      com.tradeflux.grpc.CoinInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tradeflux.grpc.CoinInfo buildPartial() {
      com.tradeflux.grpc.CoinInfo result = new com.tradeflux.grpc.CoinInfo(this);
      int from_bitField0_ = bitField0_;
      result.symbol_ = symbol_;
      result.baseAsset_ = baseAsset_;
      result.quoteAsset_ = quoteAsset_;
      if (((bitField0_ & 0x00000001) != 0)) {
        orderTypes_ = java.util.Collections.unmodifiableList(orderTypes_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.orderTypes_ = orderTypes_;
      result.isMarginTradingAllowed_ = isMarginTradingAllowed_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tradeflux.grpc.CoinInfo) {
        return mergeFrom((com.tradeflux.grpc.CoinInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tradeflux.grpc.CoinInfo other) {
      if (other == com.tradeflux.grpc.CoinInfo.getDefaultInstance()) return this;
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        onChanged();
      }
      if (!other.getBaseAsset().isEmpty()) {
        baseAsset_ = other.baseAsset_;
        onChanged();
      }
      if (!other.getQuoteAsset().isEmpty()) {
        quoteAsset_ = other.quoteAsset_;
        onChanged();
      }
      if (!other.orderTypes_.isEmpty()) {
        if (orderTypes_.isEmpty()) {
          orderTypes_ = other.orderTypes_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureOrderTypesIsMutable();
          orderTypes_.addAll(other.orderTypes_);
        }
        onChanged();
      }
      if (other.getIsMarginTradingAllowed() != false) {
        setIsMarginTradingAllowed(other.getIsMarginTradingAllowed());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tradeflux.grpc.CoinInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tradeflux.grpc.CoinInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object symbol_ = "";
    /**
     * <code>string symbol = 1;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string symbol = 1;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      symbol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      
      symbol_ = getDefaultInstance().getSymbol();
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 1;</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      symbol_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object baseAsset_ = "";
    /**
     * <code>string base_asset = 2;</code>
     * @return The baseAsset.
     */
    public java.lang.String getBaseAsset() {
      java.lang.Object ref = baseAsset_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        baseAsset_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string base_asset = 2;</code>
     * @return The bytes for baseAsset.
     */
    public com.google.protobuf.ByteString
        getBaseAssetBytes() {
      java.lang.Object ref = baseAsset_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        baseAsset_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string base_asset = 2;</code>
     * @param value The baseAsset to set.
     * @return This builder for chaining.
     */
    public Builder setBaseAsset(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      baseAsset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string base_asset = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBaseAsset() {
      
      baseAsset_ = getDefaultInstance().getBaseAsset();
      onChanged();
      return this;
    }
    /**
     * <code>string base_asset = 2;</code>
     * @param value The bytes for baseAsset to set.
     * @return This builder for chaining.
     */
    public Builder setBaseAssetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      baseAsset_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object quoteAsset_ = "";
    /**
     * <code>string quote_asset = 3;</code>
     * @return The quoteAsset.
     */
    public java.lang.String getQuoteAsset() {
      java.lang.Object ref = quoteAsset_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        quoteAsset_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string quote_asset = 3;</code>
     * @return The bytes for quoteAsset.
     */
    public com.google.protobuf.ByteString
        getQuoteAssetBytes() {
      java.lang.Object ref = quoteAsset_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        quoteAsset_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string quote_asset = 3;</code>
     * @param value The quoteAsset to set.
     * @return This builder for chaining.
     */
    public Builder setQuoteAsset(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      quoteAsset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string quote_asset = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuoteAsset() {
      
      quoteAsset_ = getDefaultInstance().getQuoteAsset();
      onChanged();
      return this;
    }
    /**
     * <code>string quote_asset = 3;</code>
     * @param value The bytes for quoteAsset to set.
     * @return This builder for chaining.
     */
    public Builder setQuoteAssetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      quoteAsset_ = value;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> orderTypes_ =
      java.util.Collections.emptyList();
    private void ensureOrderTypesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        orderTypes_ = new java.util.ArrayList<java.lang.Integer>(orderTypes_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
     * @return A list containing the orderTypes.
     */
    public java.util.List<com.tradeflux.grpc.OrderTypes> getOrderTypesList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, com.tradeflux.grpc.OrderTypes>(orderTypes_, orderTypes_converter_);
    }
    /**
     * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
     * @return The count of orderTypes.
     */
    public int getOrderTypesCount() {
      return orderTypes_.size();
    }
    /**
     * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
     * @param index The index of the element to return.
     * @return The orderTypes at the given index.
     */
    public com.tradeflux.grpc.OrderTypes getOrderTypes(int index) {
      return orderTypes_converter_.convert(orderTypes_.get(index));
    }
    /**
     * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
     * @param index The index to set the value at.
     * @param value The orderTypes to set.
     * @return This builder for chaining.
     */
    public Builder setOrderTypes(
        int index, com.tradeflux.grpc.OrderTypes value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureOrderTypesIsMutable();
      orderTypes_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
     * @param value The orderTypes to add.
     * @return This builder for chaining.
     */
    public Builder addOrderTypes(com.tradeflux.grpc.OrderTypes value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureOrderTypesIsMutable();
      orderTypes_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
     * @param values The orderTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllOrderTypes(
        java.lang.Iterable<? extends com.tradeflux.grpc.OrderTypes> values) {
      ensureOrderTypesIsMutable();
      for (com.tradeflux.grpc.OrderTypes value : values) {
        orderTypes_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderTypes() {
      orderTypes_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
     * @return A list containing the enum numeric values on the wire for orderTypes.
     */
    public java.util.List<java.lang.Integer>
    getOrderTypesValueList() {
      return java.util.Collections.unmodifiableList(orderTypes_);
    }
    /**
     * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of orderTypes at the given index.
     */
    public int getOrderTypesValue(int index) {
      return orderTypes_.get(index);
    }
    /**
     * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of orderTypes at the given index.
     * @return This builder for chaining.
     */
    public Builder setOrderTypesValue(
        int index, int value) {
      ensureOrderTypesIsMutable();
      orderTypes_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
     * @param value The enum numeric value on the wire for orderTypes to add.
     * @return This builder for chaining.
     */
    public Builder addOrderTypesValue(int value) {
      ensureOrderTypesIsMutable();
      orderTypes_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .tradeflux.OrderTypes order_types = 4;</code>
     * @param values The enum numeric values on the wire for orderTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllOrderTypesValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureOrderTypesIsMutable();
      for (int value : values) {
        orderTypes_.add(value);
      }
      onChanged();
      return this;
    }

    private boolean isMarginTradingAllowed_ ;
    /**
     * <code>bool is_margin_trading_allowed = 5;</code>
     * @return The isMarginTradingAllowed.
     */
    @java.lang.Override
    public boolean getIsMarginTradingAllowed() {
      return isMarginTradingAllowed_;
    }
    /**
     * <code>bool is_margin_trading_allowed = 5;</code>
     * @param value The isMarginTradingAllowed to set.
     * @return This builder for chaining.
     */
    public Builder setIsMarginTradingAllowed(boolean value) {
      
      isMarginTradingAllowed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_margin_trading_allowed = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsMarginTradingAllowed() {
      
      isMarginTradingAllowed_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tradeflux.CoinInfo)
  }

  // @@protoc_insertion_point(class_scope:tradeflux.CoinInfo)
  private static final com.tradeflux.grpc.CoinInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tradeflux.grpc.CoinInfo();
  }

  public static com.tradeflux.grpc.CoinInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CoinInfo>
      PARSER = new com.google.protobuf.AbstractParser<CoinInfo>() {
    @java.lang.Override
    public CoinInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CoinInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CoinInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CoinInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tradeflux.grpc.CoinInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

