// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

public interface CoinPriceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tradeflux.CoinPrice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>double price = 2;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>int32 average_price_interval_mins = 3;</code>
   * @return Whether the averagePriceIntervalMins field is set.
   */
  boolean hasAveragePriceIntervalMins();
  /**
   * <code>int32 average_price_interval_mins = 3;</code>
   * @return The averagePriceIntervalMins.
   */
  int getAveragePriceIntervalMins();

  /**
   * <code>int64 last_trade_time = 4;</code>
   * @return Whether the lastTradeTime field is set.
   */
  boolean hasLastTradeTime();
  /**
   * <code>int64 last_trade_time = 4;</code>
   * @return The lastTradeTime.
   */
  long getLastTradeTime();

  /**
   * <code>int64 event_time = 5;</code>
   * @return Whether the eventTime field is set.
   */
  boolean hasEventTime();
  /**
   * <code>int64 event_time = 5;</code>
   * @return The eventTime.
   */
  long getEventTime();
}
