// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

public interface CoinListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tradeflux.CoinListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tradeflux.CoinInfo coins = 1;</code>
   */
  java.util.List<com.tradeflux.grpc.CoinInfo> 
      getCoinsList();
  /**
   * <code>repeated .tradeflux.CoinInfo coins = 1;</code>
   */
  com.tradeflux.grpc.CoinInfo getCoins(int index);
  /**
   * <code>repeated .tradeflux.CoinInfo coins = 1;</code>
   */
  int getCoinsCount();
  /**
   * <code>repeated .tradeflux.CoinInfo coins = 1;</code>
   */
  java.util.List<? extends com.tradeflux.grpc.CoinInfoOrBuilder> 
      getCoinsOrBuilderList();
  /**
   * <code>repeated .tradeflux.CoinInfo coins = 1;</code>
   */
  com.tradeflux.grpc.CoinInfoOrBuilder getCoinsOrBuilder(
      int index);
}
