// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

public interface EmptyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tradeflux.EmptyRequest)
    com.google.protobuf.MessageOrBuilder {
}
