// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

/**
 * Protobuf type {@code tradeflux.HistoricalOHLCResponse}
 */
public final class HistoricalOHLCResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tradeflux.HistoricalOHLCResponse)
    HistoricalOHLCResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HistoricalOHLCResponse.newBuilder() to construct.
  private HistoricalOHLCResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HistoricalOHLCResponse() {
    oHLCData_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HistoricalOHLCResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HistoricalOHLCResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              oHLCData_ = new java.util.ArrayList<com.tradeflux.grpc.OHLCData>();
              mutable_bitField0_ |= 0x00000001;
            }
            oHLCData_.add(
                input.readMessage(com.tradeflux.grpc.OHLCData.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        oHLCData_ = java.util.Collections.unmodifiableList(oHLCData_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_HistoricalOHLCResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_HistoricalOHLCResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tradeflux.grpc.HistoricalOHLCResponse.class, com.tradeflux.grpc.HistoricalOHLCResponse.Builder.class);
  }

  public static final int OHLC_DATA_FIELD_NUMBER = 1;
  private java.util.List<com.tradeflux.grpc.OHLCData> oHLCData_;
  /**
   * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.tradeflux.grpc.OHLCData> getOHLCDataList() {
    return oHLCData_;
  }
  /**
   * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.tradeflux.grpc.OHLCDataOrBuilder> 
      getOHLCDataOrBuilderList() {
    return oHLCData_;
  }
  /**
   * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
   */
  @java.lang.Override
  public int getOHLCDataCount() {
    return oHLCData_.size();
  }
  /**
   * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
   */
  @java.lang.Override
  public com.tradeflux.grpc.OHLCData getOHLCData(int index) {
    return oHLCData_.get(index);
  }
  /**
   * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
   */
  @java.lang.Override
  public com.tradeflux.grpc.OHLCDataOrBuilder getOHLCDataOrBuilder(
      int index) {
    return oHLCData_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < oHLCData_.size(); i++) {
      output.writeMessage(1, oHLCData_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < oHLCData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, oHLCData_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tradeflux.grpc.HistoricalOHLCResponse)) {
      return super.equals(obj);
    }
    com.tradeflux.grpc.HistoricalOHLCResponse other = (com.tradeflux.grpc.HistoricalOHLCResponse) obj;

    if (!getOHLCDataList()
        .equals(other.getOHLCDataList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getOHLCDataCount() > 0) {
      hash = (37 * hash) + OHLC_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getOHLCDataList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tradeflux.grpc.HistoricalOHLCResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.HistoricalOHLCResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.HistoricalOHLCResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.HistoricalOHLCResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.HistoricalOHLCResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.HistoricalOHLCResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.HistoricalOHLCResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.HistoricalOHLCResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tradeflux.grpc.HistoricalOHLCResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.HistoricalOHLCResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tradeflux.grpc.HistoricalOHLCResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.HistoricalOHLCResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tradeflux.grpc.HistoricalOHLCResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tradeflux.HistoricalOHLCResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tradeflux.HistoricalOHLCResponse)
      com.tradeflux.grpc.HistoricalOHLCResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_HistoricalOHLCResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_HistoricalOHLCResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tradeflux.grpc.HistoricalOHLCResponse.class, com.tradeflux.grpc.HistoricalOHLCResponse.Builder.class);
    }

    // Construct using com.tradeflux.grpc.HistoricalOHLCResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOHLCDataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (oHLCDataBuilder_ == null) {
        oHLCData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        oHLCDataBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_HistoricalOHLCResponse_descriptor;
    }

    @java.lang.Override
    public com.tradeflux.grpc.HistoricalOHLCResponse getDefaultInstanceForType() {
      return com.tradeflux.grpc.HistoricalOHLCResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.tradeflux.grpc.HistoricalOHLCResponse build() {
      com.tradeflux.grpc.HistoricalOHLCResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tradeflux.grpc.HistoricalOHLCResponse buildPartial() {
      com.tradeflux.grpc.HistoricalOHLCResponse result = new com.tradeflux.grpc.HistoricalOHLCResponse(this);
      int from_bitField0_ = bitField0_;
      if (oHLCDataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          oHLCData_ = java.util.Collections.unmodifiableList(oHLCData_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.oHLCData_ = oHLCData_;
      } else {
        result.oHLCData_ = oHLCDataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tradeflux.grpc.HistoricalOHLCResponse) {
        return mergeFrom((com.tradeflux.grpc.HistoricalOHLCResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tradeflux.grpc.HistoricalOHLCResponse other) {
      if (other == com.tradeflux.grpc.HistoricalOHLCResponse.getDefaultInstance()) return this;
      if (oHLCDataBuilder_ == null) {
        if (!other.oHLCData_.isEmpty()) {
          if (oHLCData_.isEmpty()) {
            oHLCData_ = other.oHLCData_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOHLCDataIsMutable();
            oHLCData_.addAll(other.oHLCData_);
          }
          onChanged();
        }
      } else {
        if (!other.oHLCData_.isEmpty()) {
          if (oHLCDataBuilder_.isEmpty()) {
            oHLCDataBuilder_.dispose();
            oHLCDataBuilder_ = null;
            oHLCData_ = other.oHLCData_;
            bitField0_ = (bitField0_ & ~0x00000001);
            oHLCDataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOHLCDataFieldBuilder() : null;
          } else {
            oHLCDataBuilder_.addAllMessages(other.oHLCData_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tradeflux.grpc.HistoricalOHLCResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tradeflux.grpc.HistoricalOHLCResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.tradeflux.grpc.OHLCData> oHLCData_ =
      java.util.Collections.emptyList();
    private void ensureOHLCDataIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        oHLCData_ = new java.util.ArrayList<com.tradeflux.grpc.OHLCData>(oHLCData_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tradeflux.grpc.OHLCData, com.tradeflux.grpc.OHLCData.Builder, com.tradeflux.grpc.OHLCDataOrBuilder> oHLCDataBuilder_;

    /**
     * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
     */
    public java.util.List<com.tradeflux.grpc.OHLCData> getOHLCDataList() {
      if (oHLCDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(oHLCData_);
      } else {
        return oHLCDataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
     */
    public int getOHLCDataCount() {
      if (oHLCDataBuilder_ == null) {
        return oHLCData_.size();
      } else {
        return oHLCDataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
     */
    public com.tradeflux.grpc.OHLCData getOHLCData(int index) {
      if (oHLCDataBuilder_ == null) {
        return oHLCData_.get(index);
      } else {
        return oHLCDataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
     */
    public Builder setOHLCData(
        int index, com.tradeflux.grpc.OHLCData value) {
      if (oHLCDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOHLCDataIsMutable();
        oHLCData_.set(index, value);
        onChanged();
      } else {
        oHLCDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
     */
    public Builder setOHLCData(
        int index, com.tradeflux.grpc.OHLCData.Builder builderForValue) {
      if (oHLCDataBuilder_ == null) {
        ensureOHLCDataIsMutable();
        oHLCData_.set(index, builderForValue.build());
        onChanged();
      } else {
        oHLCDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
     */
    public Builder addOHLCData(com.tradeflux.grpc.OHLCData value) {
      if (oHLCDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOHLCDataIsMutable();
        oHLCData_.add(value);
        onChanged();
      } else {
        oHLCDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
     */
    public Builder addOHLCData(
        int index, com.tradeflux.grpc.OHLCData value) {
      if (oHLCDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOHLCDataIsMutable();
        oHLCData_.add(index, value);
        onChanged();
      } else {
        oHLCDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
     */
    public Builder addOHLCData(
        com.tradeflux.grpc.OHLCData.Builder builderForValue) {
      if (oHLCDataBuilder_ == null) {
        ensureOHLCDataIsMutable();
        oHLCData_.add(builderForValue.build());
        onChanged();
      } else {
        oHLCDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
     */
    public Builder addOHLCData(
        int index, com.tradeflux.grpc.OHLCData.Builder builderForValue) {
      if (oHLCDataBuilder_ == null) {
        ensureOHLCDataIsMutable();
        oHLCData_.add(index, builderForValue.build());
        onChanged();
      } else {
        oHLCDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
     */
    public Builder addAllOHLCData(
        java.lang.Iterable<? extends com.tradeflux.grpc.OHLCData> values) {
      if (oHLCDataBuilder_ == null) {
        ensureOHLCDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, oHLCData_);
        onChanged();
      } else {
        oHLCDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
     */
    public Builder clearOHLCData() {
      if (oHLCDataBuilder_ == null) {
        oHLCData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        oHLCDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
     */
    public Builder removeOHLCData(int index) {
      if (oHLCDataBuilder_ == null) {
        ensureOHLCDataIsMutable();
        oHLCData_.remove(index);
        onChanged();
      } else {
        oHLCDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
     */
    public com.tradeflux.grpc.OHLCData.Builder getOHLCDataBuilder(
        int index) {
      return getOHLCDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
     */
    public com.tradeflux.grpc.OHLCDataOrBuilder getOHLCDataOrBuilder(
        int index) {
      if (oHLCDataBuilder_ == null) {
        return oHLCData_.get(index);  } else {
        return oHLCDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
     */
    public java.util.List<? extends com.tradeflux.grpc.OHLCDataOrBuilder> 
         getOHLCDataOrBuilderList() {
      if (oHLCDataBuilder_ != null) {
        return oHLCDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(oHLCData_);
      }
    }
    /**
     * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
     */
    public com.tradeflux.grpc.OHLCData.Builder addOHLCDataBuilder() {
      return getOHLCDataFieldBuilder().addBuilder(
          com.tradeflux.grpc.OHLCData.getDefaultInstance());
    }
    /**
     * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
     */
    public com.tradeflux.grpc.OHLCData.Builder addOHLCDataBuilder(
        int index) {
      return getOHLCDataFieldBuilder().addBuilder(
          index, com.tradeflux.grpc.OHLCData.getDefaultInstance());
    }
    /**
     * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
     */
    public java.util.List<com.tradeflux.grpc.OHLCData.Builder> 
         getOHLCDataBuilderList() {
      return getOHLCDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tradeflux.grpc.OHLCData, com.tradeflux.grpc.OHLCData.Builder, com.tradeflux.grpc.OHLCDataOrBuilder> 
        getOHLCDataFieldBuilder() {
      if (oHLCDataBuilder_ == null) {
        oHLCDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.tradeflux.grpc.OHLCData, com.tradeflux.grpc.OHLCData.Builder, com.tradeflux.grpc.OHLCDataOrBuilder>(
                oHLCData_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        oHLCData_ = null;
      }
      return oHLCDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tradeflux.HistoricalOHLCResponse)
  }

  // @@protoc_insertion_point(class_scope:tradeflux.HistoricalOHLCResponse)
  private static final com.tradeflux.grpc.HistoricalOHLCResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tradeflux.grpc.HistoricalOHLCResponse();
  }

  public static com.tradeflux.grpc.HistoricalOHLCResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HistoricalOHLCResponse>
      PARSER = new com.google.protobuf.AbstractParser<HistoricalOHLCResponse>() {
    @java.lang.Override
    public HistoricalOHLCResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HistoricalOHLCResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HistoricalOHLCResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HistoricalOHLCResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tradeflux.grpc.HistoricalOHLCResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

