// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

public interface HistoricalOHLCResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tradeflux.HistoricalOHLCResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
   */
  java.util.List<com.tradeflux.grpc.OHLCData> 
      getOHLCDataList();
  /**
   * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
   */
  com.tradeflux.grpc.OHLCData getOHLCData(int index);
  /**
   * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
   */
  int getOHLCDataCount();
  /**
   * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
   */
  java.util.List<? extends com.tradeflux.grpc.OHLCDataOrBuilder> 
      getOHLCDataOrBuilderList();
  /**
   * <code>repeated .tradeflux.OHLCData OHLC_data = 1;</code>
   */
  com.tradeflux.grpc.OHLCDataOrBuilder getOHLCDataOrBuilder(
      int index);
}
