// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

public interface NBBOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tradeflux.NBBO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>double bid_price = 2;</code>
   * @return The bidPrice.
   */
  double getBidPrice();

  /**
   * <code>double bid_quantity = 3;</code>
   * @return The bidQuantity.
   */
  double getBidQuantity();

  /**
   * <code>double ask_price = 4;</code>
   * @return The askPrice.
   */
  double getAskPrice();

  /**
   * <code>double ask_quantity = 5;</code>
   * @return The askQuantity.
   */
  double getAskQuantity();
}
