// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

/**
 * Protobuf type {@code tradeflux.NBBO}
 */
public final class NBBO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tradeflux.NBBO)
    NBBOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NBBO.newBuilder() to construct.
  private NBBO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NBBO() {
    symbol_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NBBO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NBBO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            symbol_ = s;
            break;
          }
          case 17: {

            bidPrice_ = input.readDouble();
            break;
          }
          case 25: {

            bidQuantity_ = input.readDouble();
            break;
          }
          case 33: {

            askPrice_ = input.readDouble();
            break;
          }
          case 41: {

            askQuantity_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_NBBO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_NBBO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tradeflux.grpc.NBBO.class, com.tradeflux.grpc.NBBO.Builder.class);
  }

  public static final int SYMBOL_FIELD_NUMBER = 1;
  private volatile java.lang.Object symbol_;
  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BID_PRICE_FIELD_NUMBER = 2;
  private double bidPrice_;
  /**
   * <code>double bid_price = 2;</code>
   * @return The bidPrice.
   */
  @java.lang.Override
  public double getBidPrice() {
    return bidPrice_;
  }

  public static final int BID_QUANTITY_FIELD_NUMBER = 3;
  private double bidQuantity_;
  /**
   * <code>double bid_quantity = 3;</code>
   * @return The bidQuantity.
   */
  @java.lang.Override
  public double getBidQuantity() {
    return bidQuantity_;
  }

  public static final int ASK_PRICE_FIELD_NUMBER = 4;
  private double askPrice_;
  /**
   * <code>double ask_price = 4;</code>
   * @return The askPrice.
   */
  @java.lang.Override
  public double getAskPrice() {
    return askPrice_;
  }

  public static final int ASK_QUANTITY_FIELD_NUMBER = 5;
  private double askQuantity_;
  /**
   * <code>double ask_quantity = 5;</code>
   * @return The askQuantity.
   */
  @java.lang.Override
  public double getAskQuantity() {
    return askQuantity_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSymbolBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, symbol_);
    }
    if (bidPrice_ != 0D) {
      output.writeDouble(2, bidPrice_);
    }
    if (bidQuantity_ != 0D) {
      output.writeDouble(3, bidQuantity_);
    }
    if (askPrice_ != 0D) {
      output.writeDouble(4, askPrice_);
    }
    if (askQuantity_ != 0D) {
      output.writeDouble(5, askQuantity_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSymbolBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, symbol_);
    }
    if (bidPrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, bidPrice_);
    }
    if (bidQuantity_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, bidQuantity_);
    }
    if (askPrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, askPrice_);
    }
    if (askQuantity_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, askQuantity_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tradeflux.grpc.NBBO)) {
      return super.equals(obj);
    }
    com.tradeflux.grpc.NBBO other = (com.tradeflux.grpc.NBBO) obj;

    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (java.lang.Double.doubleToLongBits(getBidPrice())
        != java.lang.Double.doubleToLongBits(
            other.getBidPrice())) return false;
    if (java.lang.Double.doubleToLongBits(getBidQuantity())
        != java.lang.Double.doubleToLongBits(
            other.getBidQuantity())) return false;
    if (java.lang.Double.doubleToLongBits(getAskPrice())
        != java.lang.Double.doubleToLongBits(
            other.getAskPrice())) return false;
    if (java.lang.Double.doubleToLongBits(getAskQuantity())
        != java.lang.Double.doubleToLongBits(
            other.getAskQuantity())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    hash = (37 * hash) + BID_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBidPrice()));
    hash = (37 * hash) + BID_QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBidQuantity()));
    hash = (37 * hash) + ASK_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAskPrice()));
    hash = (37 * hash) + ASK_QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAskQuantity()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tradeflux.grpc.NBBO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.NBBO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.NBBO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.NBBO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.NBBO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.NBBO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.NBBO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.NBBO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tradeflux.grpc.NBBO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.NBBO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tradeflux.grpc.NBBO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.NBBO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tradeflux.grpc.NBBO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tradeflux.NBBO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tradeflux.NBBO)
      com.tradeflux.grpc.NBBOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_NBBO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_NBBO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tradeflux.grpc.NBBO.class, com.tradeflux.grpc.NBBO.Builder.class);
    }

    // Construct using com.tradeflux.grpc.NBBO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      symbol_ = "";

      bidPrice_ = 0D;

      bidQuantity_ = 0D;

      askPrice_ = 0D;

      askQuantity_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_NBBO_descriptor;
    }

    @java.lang.Override
    public com.tradeflux.grpc.NBBO getDefaultInstanceForType() {
      return com.tradeflux.grpc.NBBO.getDefaultInstance();
    }

    @java.lang.Override
    public com.tradeflux.grpc.NBBO build() {
      com.tradeflux.grpc.NBBO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tradeflux.grpc.NBBO buildPartial() {
      com.tradeflux.grpc.NBBO result = new com.tradeflux.grpc.NBBO(this);
      result.symbol_ = symbol_;
      result.bidPrice_ = bidPrice_;
      result.bidQuantity_ = bidQuantity_;
      result.askPrice_ = askPrice_;
      result.askQuantity_ = askQuantity_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tradeflux.grpc.NBBO) {
        return mergeFrom((com.tradeflux.grpc.NBBO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tradeflux.grpc.NBBO other) {
      if (other == com.tradeflux.grpc.NBBO.getDefaultInstance()) return this;
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        onChanged();
      }
      if (other.getBidPrice() != 0D) {
        setBidPrice(other.getBidPrice());
      }
      if (other.getBidQuantity() != 0D) {
        setBidQuantity(other.getBidQuantity());
      }
      if (other.getAskPrice() != 0D) {
        setAskPrice(other.getAskPrice());
      }
      if (other.getAskQuantity() != 0D) {
        setAskQuantity(other.getAskQuantity());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tradeflux.grpc.NBBO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tradeflux.grpc.NBBO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object symbol_ = "";
    /**
     * <code>string symbol = 1;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string symbol = 1;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      symbol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      
      symbol_ = getDefaultInstance().getSymbol();
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 1;</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      symbol_ = value;
      onChanged();
      return this;
    }

    private double bidPrice_ ;
    /**
     * <code>double bid_price = 2;</code>
     * @return The bidPrice.
     */
    @java.lang.Override
    public double getBidPrice() {
      return bidPrice_;
    }
    /**
     * <code>double bid_price = 2;</code>
     * @param value The bidPrice to set.
     * @return This builder for chaining.
     */
    public Builder setBidPrice(double value) {
      
      bidPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double bid_price = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBidPrice() {
      
      bidPrice_ = 0D;
      onChanged();
      return this;
    }

    private double bidQuantity_ ;
    /**
     * <code>double bid_quantity = 3;</code>
     * @return The bidQuantity.
     */
    @java.lang.Override
    public double getBidQuantity() {
      return bidQuantity_;
    }
    /**
     * <code>double bid_quantity = 3;</code>
     * @param value The bidQuantity to set.
     * @return This builder for chaining.
     */
    public Builder setBidQuantity(double value) {
      
      bidQuantity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double bid_quantity = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBidQuantity() {
      
      bidQuantity_ = 0D;
      onChanged();
      return this;
    }

    private double askPrice_ ;
    /**
     * <code>double ask_price = 4;</code>
     * @return The askPrice.
     */
    @java.lang.Override
    public double getAskPrice() {
      return askPrice_;
    }
    /**
     * <code>double ask_price = 4;</code>
     * @param value The askPrice to set.
     * @return This builder for chaining.
     */
    public Builder setAskPrice(double value) {
      
      askPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double ask_price = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAskPrice() {
      
      askPrice_ = 0D;
      onChanged();
      return this;
    }

    private double askQuantity_ ;
    /**
     * <code>double ask_quantity = 5;</code>
     * @return The askQuantity.
     */
    @java.lang.Override
    public double getAskQuantity() {
      return askQuantity_;
    }
    /**
     * <code>double ask_quantity = 5;</code>
     * @param value The askQuantity to set.
     * @return This builder for chaining.
     */
    public Builder setAskQuantity(double value) {
      
      askQuantity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double ask_quantity = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAskQuantity() {
      
      askQuantity_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tradeflux.NBBO)
  }

  // @@protoc_insertion_point(class_scope:tradeflux.NBBO)
  private static final com.tradeflux.grpc.NBBO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tradeflux.grpc.NBBO();
  }

  public static com.tradeflux.grpc.NBBO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NBBO>
      PARSER = new com.google.protobuf.AbstractParser<NBBO>() {
    @java.lang.Override
    public NBBO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NBBO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NBBO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NBBO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tradeflux.grpc.NBBO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

