// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

public interface OHLCDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tradeflux.OHLCData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 kline_open_time = 1;</code>
   * @return The klineOpenTime.
   */
  long getKlineOpenTime();

  /**
   * <code>double open_price = 2;</code>
   * @return The openPrice.
   */
  double getOpenPrice();

  /**
   * <code>double high_price = 3;</code>
   * @return The highPrice.
   */
  double getHighPrice();

  /**
   * <code>double low_price = 4;</code>
   * @return The lowPrice.
   */
  double getLowPrice();

  /**
   * <code>double volume = 5;</code>
   * @return The volume.
   */
  double getVolume();

  /**
   * <code>int64 kline_close_time = 6;</code>
   * @return The klineCloseTime.
   */
  long getKlineCloseTime();

  /**
   * <code>double quote_asset_volume = 7;</code>
   * @return The quoteAssetVolume.
   */
  double getQuoteAssetVolume();

  /**
   * <code>int64 number_of_trades = 8;</code>
   * @return The numberOfTrades.
   */
  long getNumberOfTrades();

  /**
   * <code>double taker_buy_asset_vol = 9;</code>
   * @return The takerBuyAssetVol.
   */
  double getTakerBuyAssetVol();

  /**
   * <code>double taker_buy_quote_asset_vol = 10;</code>
   * @return The takerBuyQuoteAssetVol.
   */
  double getTakerBuyQuoteAssetVol();
}
