// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

/**
 * Protobuf type {@code tradeflux.OHLCDataResponse}
 */
public final class OHLCDataResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tradeflux.OHLCDataResponse)
    OHLCDataResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OHLCDataResponse.newBuilder() to construct.
  private OHLCDataResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OHLCDataResponse() {
    symbol_ = "";
    interval_ = "";
    candles_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OHLCDataResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OHLCDataResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            symbol_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            interval_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              candles_ = new java.util.ArrayList<com.tradeflux.grpc.OHLCData>();
              mutable_bitField0_ |= 0x00000001;
            }
            candles_.add(
                input.readMessage(com.tradeflux.grpc.OHLCData.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        candles_ = java.util.Collections.unmodifiableList(candles_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_OHLCDataResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_OHLCDataResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tradeflux.grpc.OHLCDataResponse.class, com.tradeflux.grpc.OHLCDataResponse.Builder.class);
  }

  public static final int SYMBOL_FIELD_NUMBER = 1;
  private volatile java.lang.Object symbol_;
  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTERVAL_FIELD_NUMBER = 2;
  private volatile java.lang.Object interval_;
  /**
   * <code>string interval = 2;</code>
   * @return The interval.
   */
  @java.lang.Override
  public java.lang.String getInterval() {
    java.lang.Object ref = interval_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      interval_ = s;
      return s;
    }
  }
  /**
   * <code>string interval = 2;</code>
   * @return The bytes for interval.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIntervalBytes() {
    java.lang.Object ref = interval_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      interval_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CANDLES_FIELD_NUMBER = 3;
  private java.util.List<com.tradeflux.grpc.OHLCData> candles_;
  /**
   * <code>repeated .tradeflux.OHLCData candles = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.tradeflux.grpc.OHLCData> getCandlesList() {
    return candles_;
  }
  /**
   * <code>repeated .tradeflux.OHLCData candles = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.tradeflux.grpc.OHLCDataOrBuilder> 
      getCandlesOrBuilderList() {
    return candles_;
  }
  /**
   * <code>repeated .tradeflux.OHLCData candles = 3;</code>
   */
  @java.lang.Override
  public int getCandlesCount() {
    return candles_.size();
  }
  /**
   * <code>repeated .tradeflux.OHLCData candles = 3;</code>
   */
  @java.lang.Override
  public com.tradeflux.grpc.OHLCData getCandles(int index) {
    return candles_.get(index);
  }
  /**
   * <code>repeated .tradeflux.OHLCData candles = 3;</code>
   */
  @java.lang.Override
  public com.tradeflux.grpc.OHLCDataOrBuilder getCandlesOrBuilder(
      int index) {
    return candles_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSymbolBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, symbol_);
    }
    if (!getIntervalBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, interval_);
    }
    for (int i = 0; i < candles_.size(); i++) {
      output.writeMessage(3, candles_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSymbolBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, symbol_);
    }
    if (!getIntervalBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, interval_);
    }
    for (int i = 0; i < candles_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, candles_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tradeflux.grpc.OHLCDataResponse)) {
      return super.equals(obj);
    }
    com.tradeflux.grpc.OHLCDataResponse other = (com.tradeflux.grpc.OHLCDataResponse) obj;

    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (!getInterval()
        .equals(other.getInterval())) return false;
    if (!getCandlesList()
        .equals(other.getCandlesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    hash = (37 * hash) + INTERVAL_FIELD_NUMBER;
    hash = (53 * hash) + getInterval().hashCode();
    if (getCandlesCount() > 0) {
      hash = (37 * hash) + CANDLES_FIELD_NUMBER;
      hash = (53 * hash) + getCandlesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tradeflux.grpc.OHLCDataResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.OHLCDataResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.OHLCDataResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.OHLCDataResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.OHLCDataResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.OHLCDataResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.OHLCDataResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.OHLCDataResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tradeflux.grpc.OHLCDataResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.OHLCDataResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tradeflux.grpc.OHLCDataResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.OHLCDataResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tradeflux.grpc.OHLCDataResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tradeflux.OHLCDataResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tradeflux.OHLCDataResponse)
      com.tradeflux.grpc.OHLCDataResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_OHLCDataResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_OHLCDataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tradeflux.grpc.OHLCDataResponse.class, com.tradeflux.grpc.OHLCDataResponse.Builder.class);
    }

    // Construct using com.tradeflux.grpc.OHLCDataResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCandlesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      symbol_ = "";

      interval_ = "";

      if (candlesBuilder_ == null) {
        candles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        candlesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_OHLCDataResponse_descriptor;
    }

    @java.lang.Override
    public com.tradeflux.grpc.OHLCDataResponse getDefaultInstanceForType() {
      return com.tradeflux.grpc.OHLCDataResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.tradeflux.grpc.OHLCDataResponse build() {
      com.tradeflux.grpc.OHLCDataResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tradeflux.grpc.OHLCDataResponse buildPartial() {
      com.tradeflux.grpc.OHLCDataResponse result = new com.tradeflux.grpc.OHLCDataResponse(this);
      int from_bitField0_ = bitField0_;
      result.symbol_ = symbol_;
      result.interval_ = interval_;
      if (candlesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          candles_ = java.util.Collections.unmodifiableList(candles_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.candles_ = candles_;
      } else {
        result.candles_ = candlesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tradeflux.grpc.OHLCDataResponse) {
        return mergeFrom((com.tradeflux.grpc.OHLCDataResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tradeflux.grpc.OHLCDataResponse other) {
      if (other == com.tradeflux.grpc.OHLCDataResponse.getDefaultInstance()) return this;
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        onChanged();
      }
      if (!other.getInterval().isEmpty()) {
        interval_ = other.interval_;
        onChanged();
      }
      if (candlesBuilder_ == null) {
        if (!other.candles_.isEmpty()) {
          if (candles_.isEmpty()) {
            candles_ = other.candles_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCandlesIsMutable();
            candles_.addAll(other.candles_);
          }
          onChanged();
        }
      } else {
        if (!other.candles_.isEmpty()) {
          if (candlesBuilder_.isEmpty()) {
            candlesBuilder_.dispose();
            candlesBuilder_ = null;
            candles_ = other.candles_;
            bitField0_ = (bitField0_ & ~0x00000001);
            candlesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCandlesFieldBuilder() : null;
          } else {
            candlesBuilder_.addAllMessages(other.candles_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tradeflux.grpc.OHLCDataResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tradeflux.grpc.OHLCDataResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object symbol_ = "";
    /**
     * <code>string symbol = 1;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string symbol = 1;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      symbol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      
      symbol_ = getDefaultInstance().getSymbol();
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 1;</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      symbol_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object interval_ = "";
    /**
     * <code>string interval = 2;</code>
     * @return The interval.
     */
    public java.lang.String getInterval() {
      java.lang.Object ref = interval_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interval_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string interval = 2;</code>
     * @return The bytes for interval.
     */
    public com.google.protobuf.ByteString
        getIntervalBytes() {
      java.lang.Object ref = interval_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interval_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string interval = 2;</code>
     * @param value The interval to set.
     * @return This builder for chaining.
     */
    public Builder setInterval(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      interval_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string interval = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearInterval() {
      
      interval_ = getDefaultInstance().getInterval();
      onChanged();
      return this;
    }
    /**
     * <code>string interval = 2;</code>
     * @param value The bytes for interval to set.
     * @return This builder for chaining.
     */
    public Builder setIntervalBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      interval_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.tradeflux.grpc.OHLCData> candles_ =
      java.util.Collections.emptyList();
    private void ensureCandlesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        candles_ = new java.util.ArrayList<com.tradeflux.grpc.OHLCData>(candles_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tradeflux.grpc.OHLCData, com.tradeflux.grpc.OHLCData.Builder, com.tradeflux.grpc.OHLCDataOrBuilder> candlesBuilder_;

    /**
     * <code>repeated .tradeflux.OHLCData candles = 3;</code>
     */
    public java.util.List<com.tradeflux.grpc.OHLCData> getCandlesList() {
      if (candlesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(candles_);
      } else {
        return candlesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tradeflux.OHLCData candles = 3;</code>
     */
    public int getCandlesCount() {
      if (candlesBuilder_ == null) {
        return candles_.size();
      } else {
        return candlesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tradeflux.OHLCData candles = 3;</code>
     */
    public com.tradeflux.grpc.OHLCData getCandles(int index) {
      if (candlesBuilder_ == null) {
        return candles_.get(index);
      } else {
        return candlesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tradeflux.OHLCData candles = 3;</code>
     */
    public Builder setCandles(
        int index, com.tradeflux.grpc.OHLCData value) {
      if (candlesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCandlesIsMutable();
        candles_.set(index, value);
        onChanged();
      } else {
        candlesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.OHLCData candles = 3;</code>
     */
    public Builder setCandles(
        int index, com.tradeflux.grpc.OHLCData.Builder builderForValue) {
      if (candlesBuilder_ == null) {
        ensureCandlesIsMutable();
        candles_.set(index, builderForValue.build());
        onChanged();
      } else {
        candlesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.OHLCData candles = 3;</code>
     */
    public Builder addCandles(com.tradeflux.grpc.OHLCData value) {
      if (candlesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCandlesIsMutable();
        candles_.add(value);
        onChanged();
      } else {
        candlesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.OHLCData candles = 3;</code>
     */
    public Builder addCandles(
        int index, com.tradeflux.grpc.OHLCData value) {
      if (candlesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCandlesIsMutable();
        candles_.add(index, value);
        onChanged();
      } else {
        candlesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.OHLCData candles = 3;</code>
     */
    public Builder addCandles(
        com.tradeflux.grpc.OHLCData.Builder builderForValue) {
      if (candlesBuilder_ == null) {
        ensureCandlesIsMutable();
        candles_.add(builderForValue.build());
        onChanged();
      } else {
        candlesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.OHLCData candles = 3;</code>
     */
    public Builder addCandles(
        int index, com.tradeflux.grpc.OHLCData.Builder builderForValue) {
      if (candlesBuilder_ == null) {
        ensureCandlesIsMutable();
        candles_.add(index, builderForValue.build());
        onChanged();
      } else {
        candlesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.OHLCData candles = 3;</code>
     */
    public Builder addAllCandles(
        java.lang.Iterable<? extends com.tradeflux.grpc.OHLCData> values) {
      if (candlesBuilder_ == null) {
        ensureCandlesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, candles_);
        onChanged();
      } else {
        candlesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.OHLCData candles = 3;</code>
     */
    public Builder clearCandles() {
      if (candlesBuilder_ == null) {
        candles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        candlesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.OHLCData candles = 3;</code>
     */
    public Builder removeCandles(int index) {
      if (candlesBuilder_ == null) {
        ensureCandlesIsMutable();
        candles_.remove(index);
        onChanged();
      } else {
        candlesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.OHLCData candles = 3;</code>
     */
    public com.tradeflux.grpc.OHLCData.Builder getCandlesBuilder(
        int index) {
      return getCandlesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tradeflux.OHLCData candles = 3;</code>
     */
    public com.tradeflux.grpc.OHLCDataOrBuilder getCandlesOrBuilder(
        int index) {
      if (candlesBuilder_ == null) {
        return candles_.get(index);  } else {
        return candlesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tradeflux.OHLCData candles = 3;</code>
     */
    public java.util.List<? extends com.tradeflux.grpc.OHLCDataOrBuilder> 
         getCandlesOrBuilderList() {
      if (candlesBuilder_ != null) {
        return candlesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(candles_);
      }
    }
    /**
     * <code>repeated .tradeflux.OHLCData candles = 3;</code>
     */
    public com.tradeflux.grpc.OHLCData.Builder addCandlesBuilder() {
      return getCandlesFieldBuilder().addBuilder(
          com.tradeflux.grpc.OHLCData.getDefaultInstance());
    }
    /**
     * <code>repeated .tradeflux.OHLCData candles = 3;</code>
     */
    public com.tradeflux.grpc.OHLCData.Builder addCandlesBuilder(
        int index) {
      return getCandlesFieldBuilder().addBuilder(
          index, com.tradeflux.grpc.OHLCData.getDefaultInstance());
    }
    /**
     * <code>repeated .tradeflux.OHLCData candles = 3;</code>
     */
    public java.util.List<com.tradeflux.grpc.OHLCData.Builder> 
         getCandlesBuilderList() {
      return getCandlesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tradeflux.grpc.OHLCData, com.tradeflux.grpc.OHLCData.Builder, com.tradeflux.grpc.OHLCDataOrBuilder> 
        getCandlesFieldBuilder() {
      if (candlesBuilder_ == null) {
        candlesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.tradeflux.grpc.OHLCData, com.tradeflux.grpc.OHLCData.Builder, com.tradeflux.grpc.OHLCDataOrBuilder>(
                candles_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        candles_ = null;
      }
      return candlesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tradeflux.OHLCDataResponse)
  }

  // @@protoc_insertion_point(class_scope:tradeflux.OHLCDataResponse)
  private static final com.tradeflux.grpc.OHLCDataResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tradeflux.grpc.OHLCDataResponse();
  }

  public static com.tradeflux.grpc.OHLCDataResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OHLCDataResponse>
      PARSER = new com.google.protobuf.AbstractParser<OHLCDataResponse>() {
    @java.lang.Override
    public OHLCDataResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OHLCDataResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OHLCDataResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OHLCDataResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tradeflux.grpc.OHLCDataResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

