// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

public interface OHLCDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tradeflux.OHLCDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>string interval = 2;</code>
   * @return The interval.
   */
  java.lang.String getInterval();
  /**
   * <code>string interval = 2;</code>
   * @return The bytes for interval.
   */
  com.google.protobuf.ByteString
      getIntervalBytes();

  /**
   * <code>repeated .tradeflux.OHLCData candles = 3;</code>
   */
  java.util.List<com.tradeflux.grpc.OHLCData> 
      getCandlesList();
  /**
   * <code>repeated .tradeflux.OHLCData candles = 3;</code>
   */
  com.tradeflux.grpc.OHLCData getCandles(int index);
  /**
   * <code>repeated .tradeflux.OHLCData candles = 3;</code>
   */
  int getCandlesCount();
  /**
   * <code>repeated .tradeflux.OHLCData candles = 3;</code>
   */
  java.util.List<? extends com.tradeflux.grpc.OHLCDataOrBuilder> 
      getCandlesOrBuilderList();
  /**
   * <code>repeated .tradeflux.OHLCData candles = 3;</code>
   */
  com.tradeflux.grpc.OHLCDataOrBuilder getCandlesOrBuilder(
      int index);
}
