// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

/**
 * Protobuf type {@code tradeflux.OHLCData}
 */
public final class OHLCData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tradeflux.OHLCData)
    OHLCDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OHLCData.newBuilder() to construct.
  private OHLCData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OHLCData() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OHLCData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OHLCData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            klineOpenTime_ = input.readInt64();
            break;
          }
          case 17: {

            openPrice_ = input.readDouble();
            break;
          }
          case 25: {

            highPrice_ = input.readDouble();
            break;
          }
          case 33: {

            lowPrice_ = input.readDouble();
            break;
          }
          case 41: {

            volume_ = input.readDouble();
            break;
          }
          case 48: {

            klineCloseTime_ = input.readInt64();
            break;
          }
          case 57: {

            quoteAssetVolume_ = input.readDouble();
            break;
          }
          case 64: {

            numberOfTrades_ = input.readInt64();
            break;
          }
          case 73: {

            takerBuyAssetVol_ = input.readDouble();
            break;
          }
          case 81: {

            takerBuyQuoteAssetVol_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_OHLCData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_OHLCData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tradeflux.grpc.OHLCData.class, com.tradeflux.grpc.OHLCData.Builder.class);
  }

  public static final int KLINE_OPEN_TIME_FIELD_NUMBER = 1;
  private long klineOpenTime_;
  /**
   * <code>int64 kline_open_time = 1;</code>
   * @return The klineOpenTime.
   */
  @java.lang.Override
  public long getKlineOpenTime() {
    return klineOpenTime_;
  }

  public static final int OPEN_PRICE_FIELD_NUMBER = 2;
  private double openPrice_;
  /**
   * <code>double open_price = 2;</code>
   * @return The openPrice.
   */
  @java.lang.Override
  public double getOpenPrice() {
    return openPrice_;
  }

  public static final int HIGH_PRICE_FIELD_NUMBER = 3;
  private double highPrice_;
  /**
   * <code>double high_price = 3;</code>
   * @return The highPrice.
   */
  @java.lang.Override
  public double getHighPrice() {
    return highPrice_;
  }

  public static final int LOW_PRICE_FIELD_NUMBER = 4;
  private double lowPrice_;
  /**
   * <code>double low_price = 4;</code>
   * @return The lowPrice.
   */
  @java.lang.Override
  public double getLowPrice() {
    return lowPrice_;
  }

  public static final int VOLUME_FIELD_NUMBER = 5;
  private double volume_;
  /**
   * <code>double volume = 5;</code>
   * @return The volume.
   */
  @java.lang.Override
  public double getVolume() {
    return volume_;
  }

  public static final int KLINE_CLOSE_TIME_FIELD_NUMBER = 6;
  private long klineCloseTime_;
  /**
   * <code>int64 kline_close_time = 6;</code>
   * @return The klineCloseTime.
   */
  @java.lang.Override
  public long getKlineCloseTime() {
    return klineCloseTime_;
  }

  public static final int QUOTE_ASSET_VOLUME_FIELD_NUMBER = 7;
  private double quoteAssetVolume_;
  /**
   * <code>double quote_asset_volume = 7;</code>
   * @return The quoteAssetVolume.
   */
  @java.lang.Override
  public double getQuoteAssetVolume() {
    return quoteAssetVolume_;
  }

  public static final int NUMBER_OF_TRADES_FIELD_NUMBER = 8;
  private long numberOfTrades_;
  /**
   * <code>int64 number_of_trades = 8;</code>
   * @return The numberOfTrades.
   */
  @java.lang.Override
  public long getNumberOfTrades() {
    return numberOfTrades_;
  }

  public static final int TAKER_BUY_ASSET_VOL_FIELD_NUMBER = 9;
  private double takerBuyAssetVol_;
  /**
   * <code>double taker_buy_asset_vol = 9;</code>
   * @return The takerBuyAssetVol.
   */
  @java.lang.Override
  public double getTakerBuyAssetVol() {
    return takerBuyAssetVol_;
  }

  public static final int TAKER_BUY_QUOTE_ASSET_VOL_FIELD_NUMBER = 10;
  private double takerBuyQuoteAssetVol_;
  /**
   * <code>double taker_buy_quote_asset_vol = 10;</code>
   * @return The takerBuyQuoteAssetVol.
   */
  @java.lang.Override
  public double getTakerBuyQuoteAssetVol() {
    return takerBuyQuoteAssetVol_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (klineOpenTime_ != 0L) {
      output.writeInt64(1, klineOpenTime_);
    }
    if (openPrice_ != 0D) {
      output.writeDouble(2, openPrice_);
    }
    if (highPrice_ != 0D) {
      output.writeDouble(3, highPrice_);
    }
    if (lowPrice_ != 0D) {
      output.writeDouble(4, lowPrice_);
    }
    if (volume_ != 0D) {
      output.writeDouble(5, volume_);
    }
    if (klineCloseTime_ != 0L) {
      output.writeInt64(6, klineCloseTime_);
    }
    if (quoteAssetVolume_ != 0D) {
      output.writeDouble(7, quoteAssetVolume_);
    }
    if (numberOfTrades_ != 0L) {
      output.writeInt64(8, numberOfTrades_);
    }
    if (takerBuyAssetVol_ != 0D) {
      output.writeDouble(9, takerBuyAssetVol_);
    }
    if (takerBuyQuoteAssetVol_ != 0D) {
      output.writeDouble(10, takerBuyQuoteAssetVol_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (klineOpenTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, klineOpenTime_);
    }
    if (openPrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, openPrice_);
    }
    if (highPrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, highPrice_);
    }
    if (lowPrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, lowPrice_);
    }
    if (volume_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, volume_);
    }
    if (klineCloseTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, klineCloseTime_);
    }
    if (quoteAssetVolume_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, quoteAssetVolume_);
    }
    if (numberOfTrades_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, numberOfTrades_);
    }
    if (takerBuyAssetVol_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, takerBuyAssetVol_);
    }
    if (takerBuyQuoteAssetVol_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(10, takerBuyQuoteAssetVol_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tradeflux.grpc.OHLCData)) {
      return super.equals(obj);
    }
    com.tradeflux.grpc.OHLCData other = (com.tradeflux.grpc.OHLCData) obj;

    if (getKlineOpenTime()
        != other.getKlineOpenTime()) return false;
    if (java.lang.Double.doubleToLongBits(getOpenPrice())
        != java.lang.Double.doubleToLongBits(
            other.getOpenPrice())) return false;
    if (java.lang.Double.doubleToLongBits(getHighPrice())
        != java.lang.Double.doubleToLongBits(
            other.getHighPrice())) return false;
    if (java.lang.Double.doubleToLongBits(getLowPrice())
        != java.lang.Double.doubleToLongBits(
            other.getLowPrice())) return false;
    if (java.lang.Double.doubleToLongBits(getVolume())
        != java.lang.Double.doubleToLongBits(
            other.getVolume())) return false;
    if (getKlineCloseTime()
        != other.getKlineCloseTime()) return false;
    if (java.lang.Double.doubleToLongBits(getQuoteAssetVolume())
        != java.lang.Double.doubleToLongBits(
            other.getQuoteAssetVolume())) return false;
    if (getNumberOfTrades()
        != other.getNumberOfTrades()) return false;
    if (java.lang.Double.doubleToLongBits(getTakerBuyAssetVol())
        != java.lang.Double.doubleToLongBits(
            other.getTakerBuyAssetVol())) return false;
    if (java.lang.Double.doubleToLongBits(getTakerBuyQuoteAssetVol())
        != java.lang.Double.doubleToLongBits(
            other.getTakerBuyQuoteAssetVol())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KLINE_OPEN_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getKlineOpenTime());
    hash = (37 * hash) + OPEN_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getOpenPrice()));
    hash = (37 * hash) + HIGH_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getHighPrice()));
    hash = (37 * hash) + LOW_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLowPrice()));
    hash = (37 * hash) + VOLUME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getVolume()));
    hash = (37 * hash) + KLINE_CLOSE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getKlineCloseTime());
    hash = (37 * hash) + QUOTE_ASSET_VOLUME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getQuoteAssetVolume()));
    hash = (37 * hash) + NUMBER_OF_TRADES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNumberOfTrades());
    hash = (37 * hash) + TAKER_BUY_ASSET_VOL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTakerBuyAssetVol()));
    hash = (37 * hash) + TAKER_BUY_QUOTE_ASSET_VOL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTakerBuyQuoteAssetVol()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tradeflux.grpc.OHLCData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.OHLCData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.OHLCData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.OHLCData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.OHLCData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.OHLCData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.OHLCData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.OHLCData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tradeflux.grpc.OHLCData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.OHLCData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tradeflux.grpc.OHLCData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.OHLCData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tradeflux.grpc.OHLCData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tradeflux.OHLCData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tradeflux.OHLCData)
      com.tradeflux.grpc.OHLCDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_OHLCData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_OHLCData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tradeflux.grpc.OHLCData.class, com.tradeflux.grpc.OHLCData.Builder.class);
    }

    // Construct using com.tradeflux.grpc.OHLCData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      klineOpenTime_ = 0L;

      openPrice_ = 0D;

      highPrice_ = 0D;

      lowPrice_ = 0D;

      volume_ = 0D;

      klineCloseTime_ = 0L;

      quoteAssetVolume_ = 0D;

      numberOfTrades_ = 0L;

      takerBuyAssetVol_ = 0D;

      takerBuyQuoteAssetVol_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_OHLCData_descriptor;
    }

    @java.lang.Override
    public com.tradeflux.grpc.OHLCData getDefaultInstanceForType() {
      return com.tradeflux.grpc.OHLCData.getDefaultInstance();
    }

    @java.lang.Override
    public com.tradeflux.grpc.OHLCData build() {
      com.tradeflux.grpc.OHLCData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tradeflux.grpc.OHLCData buildPartial() {
      com.tradeflux.grpc.OHLCData result = new com.tradeflux.grpc.OHLCData(this);
      result.klineOpenTime_ = klineOpenTime_;
      result.openPrice_ = openPrice_;
      result.highPrice_ = highPrice_;
      result.lowPrice_ = lowPrice_;
      result.volume_ = volume_;
      result.klineCloseTime_ = klineCloseTime_;
      result.quoteAssetVolume_ = quoteAssetVolume_;
      result.numberOfTrades_ = numberOfTrades_;
      result.takerBuyAssetVol_ = takerBuyAssetVol_;
      result.takerBuyQuoteAssetVol_ = takerBuyQuoteAssetVol_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tradeflux.grpc.OHLCData) {
        return mergeFrom((com.tradeflux.grpc.OHLCData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tradeflux.grpc.OHLCData other) {
      if (other == com.tradeflux.grpc.OHLCData.getDefaultInstance()) return this;
      if (other.getKlineOpenTime() != 0L) {
        setKlineOpenTime(other.getKlineOpenTime());
      }
      if (other.getOpenPrice() != 0D) {
        setOpenPrice(other.getOpenPrice());
      }
      if (other.getHighPrice() != 0D) {
        setHighPrice(other.getHighPrice());
      }
      if (other.getLowPrice() != 0D) {
        setLowPrice(other.getLowPrice());
      }
      if (other.getVolume() != 0D) {
        setVolume(other.getVolume());
      }
      if (other.getKlineCloseTime() != 0L) {
        setKlineCloseTime(other.getKlineCloseTime());
      }
      if (other.getQuoteAssetVolume() != 0D) {
        setQuoteAssetVolume(other.getQuoteAssetVolume());
      }
      if (other.getNumberOfTrades() != 0L) {
        setNumberOfTrades(other.getNumberOfTrades());
      }
      if (other.getTakerBuyAssetVol() != 0D) {
        setTakerBuyAssetVol(other.getTakerBuyAssetVol());
      }
      if (other.getTakerBuyQuoteAssetVol() != 0D) {
        setTakerBuyQuoteAssetVol(other.getTakerBuyQuoteAssetVol());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tradeflux.grpc.OHLCData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tradeflux.grpc.OHLCData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long klineOpenTime_ ;
    /**
     * <code>int64 kline_open_time = 1;</code>
     * @return The klineOpenTime.
     */
    @java.lang.Override
    public long getKlineOpenTime() {
      return klineOpenTime_;
    }
    /**
     * <code>int64 kline_open_time = 1;</code>
     * @param value The klineOpenTime to set.
     * @return This builder for chaining.
     */
    public Builder setKlineOpenTime(long value) {
      
      klineOpenTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 kline_open_time = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKlineOpenTime() {
      
      klineOpenTime_ = 0L;
      onChanged();
      return this;
    }

    private double openPrice_ ;
    /**
     * <code>double open_price = 2;</code>
     * @return The openPrice.
     */
    @java.lang.Override
    public double getOpenPrice() {
      return openPrice_;
    }
    /**
     * <code>double open_price = 2;</code>
     * @param value The openPrice to set.
     * @return This builder for chaining.
     */
    public Builder setOpenPrice(double value) {
      
      openPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double open_price = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOpenPrice() {
      
      openPrice_ = 0D;
      onChanged();
      return this;
    }

    private double highPrice_ ;
    /**
     * <code>double high_price = 3;</code>
     * @return The highPrice.
     */
    @java.lang.Override
    public double getHighPrice() {
      return highPrice_;
    }
    /**
     * <code>double high_price = 3;</code>
     * @param value The highPrice to set.
     * @return This builder for chaining.
     */
    public Builder setHighPrice(double value) {
      
      highPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double high_price = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHighPrice() {
      
      highPrice_ = 0D;
      onChanged();
      return this;
    }

    private double lowPrice_ ;
    /**
     * <code>double low_price = 4;</code>
     * @return The lowPrice.
     */
    @java.lang.Override
    public double getLowPrice() {
      return lowPrice_;
    }
    /**
     * <code>double low_price = 4;</code>
     * @param value The lowPrice to set.
     * @return This builder for chaining.
     */
    public Builder setLowPrice(double value) {
      
      lowPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double low_price = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLowPrice() {
      
      lowPrice_ = 0D;
      onChanged();
      return this;
    }

    private double volume_ ;
    /**
     * <code>double volume = 5;</code>
     * @return The volume.
     */
    @java.lang.Override
    public double getVolume() {
      return volume_;
    }
    /**
     * <code>double volume = 5;</code>
     * @param value The volume to set.
     * @return This builder for chaining.
     */
    public Builder setVolume(double value) {
      
      volume_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double volume = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearVolume() {
      
      volume_ = 0D;
      onChanged();
      return this;
    }

    private long klineCloseTime_ ;
    /**
     * <code>int64 kline_close_time = 6;</code>
     * @return The klineCloseTime.
     */
    @java.lang.Override
    public long getKlineCloseTime() {
      return klineCloseTime_;
    }
    /**
     * <code>int64 kline_close_time = 6;</code>
     * @param value The klineCloseTime to set.
     * @return This builder for chaining.
     */
    public Builder setKlineCloseTime(long value) {
      
      klineCloseTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 kline_close_time = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearKlineCloseTime() {
      
      klineCloseTime_ = 0L;
      onChanged();
      return this;
    }

    private double quoteAssetVolume_ ;
    /**
     * <code>double quote_asset_volume = 7;</code>
     * @return The quoteAssetVolume.
     */
    @java.lang.Override
    public double getQuoteAssetVolume() {
      return quoteAssetVolume_;
    }
    /**
     * <code>double quote_asset_volume = 7;</code>
     * @param value The quoteAssetVolume to set.
     * @return This builder for chaining.
     */
    public Builder setQuoteAssetVolume(double value) {
      
      quoteAssetVolume_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double quote_asset_volume = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuoteAssetVolume() {
      
      quoteAssetVolume_ = 0D;
      onChanged();
      return this;
    }

    private long numberOfTrades_ ;
    /**
     * <code>int64 number_of_trades = 8;</code>
     * @return The numberOfTrades.
     */
    @java.lang.Override
    public long getNumberOfTrades() {
      return numberOfTrades_;
    }
    /**
     * <code>int64 number_of_trades = 8;</code>
     * @param value The numberOfTrades to set.
     * @return This builder for chaining.
     */
    public Builder setNumberOfTrades(long value) {
      
      numberOfTrades_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 number_of_trades = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumberOfTrades() {
      
      numberOfTrades_ = 0L;
      onChanged();
      return this;
    }

    private double takerBuyAssetVol_ ;
    /**
     * <code>double taker_buy_asset_vol = 9;</code>
     * @return The takerBuyAssetVol.
     */
    @java.lang.Override
    public double getTakerBuyAssetVol() {
      return takerBuyAssetVol_;
    }
    /**
     * <code>double taker_buy_asset_vol = 9;</code>
     * @param value The takerBuyAssetVol to set.
     * @return This builder for chaining.
     */
    public Builder setTakerBuyAssetVol(double value) {
      
      takerBuyAssetVol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double taker_buy_asset_vol = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTakerBuyAssetVol() {
      
      takerBuyAssetVol_ = 0D;
      onChanged();
      return this;
    }

    private double takerBuyQuoteAssetVol_ ;
    /**
     * <code>double taker_buy_quote_asset_vol = 10;</code>
     * @return The takerBuyQuoteAssetVol.
     */
    @java.lang.Override
    public double getTakerBuyQuoteAssetVol() {
      return takerBuyQuoteAssetVol_;
    }
    /**
     * <code>double taker_buy_quote_asset_vol = 10;</code>
     * @param value The takerBuyQuoteAssetVol to set.
     * @return This builder for chaining.
     */
    public Builder setTakerBuyQuoteAssetVol(double value) {
      
      takerBuyQuoteAssetVol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double taker_buy_quote_asset_vol = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearTakerBuyQuoteAssetVol() {
      
      takerBuyQuoteAssetVol_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tradeflux.OHLCData)
  }

  // @@protoc_insertion_point(class_scope:tradeflux.OHLCData)
  private static final com.tradeflux.grpc.OHLCData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tradeflux.grpc.OHLCData();
  }

  public static com.tradeflux.grpc.OHLCData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OHLCData>
      PARSER = new com.google.protobuf.AbstractParser<OHLCData>() {
    @java.lang.Override
    public OHLCData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OHLCData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OHLCData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OHLCData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tradeflux.grpc.OHLCData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

