// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

/**
 * Protobuf type {@code tradeflux.PriceResponse}
 */
public final class PriceResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tradeflux.PriceResponse)
    PriceResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PriceResponse.newBuilder() to construct.
  private PriceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PriceResponse() {
    coinPrices_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PriceResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PriceResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              coinPrices_ = new java.util.ArrayList<com.tradeflux.grpc.CoinPrice>();
              mutable_bitField0_ |= 0x00000001;
            }
            coinPrices_.add(
                input.readMessage(com.tradeflux.grpc.CoinPrice.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        coinPrices_ = java.util.Collections.unmodifiableList(coinPrices_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_PriceResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_PriceResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tradeflux.grpc.PriceResponse.class, com.tradeflux.grpc.PriceResponse.Builder.class);
  }

  public static final int COIN_PRICES_FIELD_NUMBER = 1;
  private java.util.List<com.tradeflux.grpc.CoinPrice> coinPrices_;
  /**
   * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.tradeflux.grpc.CoinPrice> getCoinPricesList() {
    return coinPrices_;
  }
  /**
   * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.tradeflux.grpc.CoinPriceOrBuilder> 
      getCoinPricesOrBuilderList() {
    return coinPrices_;
  }
  /**
   * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
   */
  @java.lang.Override
  public int getCoinPricesCount() {
    return coinPrices_.size();
  }
  /**
   * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
   */
  @java.lang.Override
  public com.tradeflux.grpc.CoinPrice getCoinPrices(int index) {
    return coinPrices_.get(index);
  }
  /**
   * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
   */
  @java.lang.Override
  public com.tradeflux.grpc.CoinPriceOrBuilder getCoinPricesOrBuilder(
      int index) {
    return coinPrices_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < coinPrices_.size(); i++) {
      output.writeMessage(1, coinPrices_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < coinPrices_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, coinPrices_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tradeflux.grpc.PriceResponse)) {
      return super.equals(obj);
    }
    com.tradeflux.grpc.PriceResponse other = (com.tradeflux.grpc.PriceResponse) obj;

    if (!getCoinPricesList()
        .equals(other.getCoinPricesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCoinPricesCount() > 0) {
      hash = (37 * hash) + COIN_PRICES_FIELD_NUMBER;
      hash = (53 * hash) + getCoinPricesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tradeflux.grpc.PriceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.PriceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.PriceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.PriceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.PriceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.PriceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.PriceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.PriceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tradeflux.grpc.PriceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.PriceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tradeflux.grpc.PriceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.PriceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tradeflux.grpc.PriceResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tradeflux.PriceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tradeflux.PriceResponse)
      com.tradeflux.grpc.PriceResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_PriceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_PriceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tradeflux.grpc.PriceResponse.class, com.tradeflux.grpc.PriceResponse.Builder.class);
    }

    // Construct using com.tradeflux.grpc.PriceResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCoinPricesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (coinPricesBuilder_ == null) {
        coinPrices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        coinPricesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_PriceResponse_descriptor;
    }

    @java.lang.Override
    public com.tradeflux.grpc.PriceResponse getDefaultInstanceForType() {
      return com.tradeflux.grpc.PriceResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.tradeflux.grpc.PriceResponse build() {
      com.tradeflux.grpc.PriceResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tradeflux.grpc.PriceResponse buildPartial() {
      com.tradeflux.grpc.PriceResponse result = new com.tradeflux.grpc.PriceResponse(this);
      int from_bitField0_ = bitField0_;
      if (coinPricesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          coinPrices_ = java.util.Collections.unmodifiableList(coinPrices_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.coinPrices_ = coinPrices_;
      } else {
        result.coinPrices_ = coinPricesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tradeflux.grpc.PriceResponse) {
        return mergeFrom((com.tradeflux.grpc.PriceResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tradeflux.grpc.PriceResponse other) {
      if (other == com.tradeflux.grpc.PriceResponse.getDefaultInstance()) return this;
      if (coinPricesBuilder_ == null) {
        if (!other.coinPrices_.isEmpty()) {
          if (coinPrices_.isEmpty()) {
            coinPrices_ = other.coinPrices_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCoinPricesIsMutable();
            coinPrices_.addAll(other.coinPrices_);
          }
          onChanged();
        }
      } else {
        if (!other.coinPrices_.isEmpty()) {
          if (coinPricesBuilder_.isEmpty()) {
            coinPricesBuilder_.dispose();
            coinPricesBuilder_ = null;
            coinPrices_ = other.coinPrices_;
            bitField0_ = (bitField0_ & ~0x00000001);
            coinPricesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCoinPricesFieldBuilder() : null;
          } else {
            coinPricesBuilder_.addAllMessages(other.coinPrices_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tradeflux.grpc.PriceResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tradeflux.grpc.PriceResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.tradeflux.grpc.CoinPrice> coinPrices_ =
      java.util.Collections.emptyList();
    private void ensureCoinPricesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        coinPrices_ = new java.util.ArrayList<com.tradeflux.grpc.CoinPrice>(coinPrices_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tradeflux.grpc.CoinPrice, com.tradeflux.grpc.CoinPrice.Builder, com.tradeflux.grpc.CoinPriceOrBuilder> coinPricesBuilder_;

    /**
     * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
     */
    public java.util.List<com.tradeflux.grpc.CoinPrice> getCoinPricesList() {
      if (coinPricesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(coinPrices_);
      } else {
        return coinPricesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
     */
    public int getCoinPricesCount() {
      if (coinPricesBuilder_ == null) {
        return coinPrices_.size();
      } else {
        return coinPricesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
     */
    public com.tradeflux.grpc.CoinPrice getCoinPrices(int index) {
      if (coinPricesBuilder_ == null) {
        return coinPrices_.get(index);
      } else {
        return coinPricesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
     */
    public Builder setCoinPrices(
        int index, com.tradeflux.grpc.CoinPrice value) {
      if (coinPricesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoinPricesIsMutable();
        coinPrices_.set(index, value);
        onChanged();
      } else {
        coinPricesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
     */
    public Builder setCoinPrices(
        int index, com.tradeflux.grpc.CoinPrice.Builder builderForValue) {
      if (coinPricesBuilder_ == null) {
        ensureCoinPricesIsMutable();
        coinPrices_.set(index, builderForValue.build());
        onChanged();
      } else {
        coinPricesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
     */
    public Builder addCoinPrices(com.tradeflux.grpc.CoinPrice value) {
      if (coinPricesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoinPricesIsMutable();
        coinPrices_.add(value);
        onChanged();
      } else {
        coinPricesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
     */
    public Builder addCoinPrices(
        int index, com.tradeflux.grpc.CoinPrice value) {
      if (coinPricesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoinPricesIsMutable();
        coinPrices_.add(index, value);
        onChanged();
      } else {
        coinPricesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
     */
    public Builder addCoinPrices(
        com.tradeflux.grpc.CoinPrice.Builder builderForValue) {
      if (coinPricesBuilder_ == null) {
        ensureCoinPricesIsMutable();
        coinPrices_.add(builderForValue.build());
        onChanged();
      } else {
        coinPricesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
     */
    public Builder addCoinPrices(
        int index, com.tradeflux.grpc.CoinPrice.Builder builderForValue) {
      if (coinPricesBuilder_ == null) {
        ensureCoinPricesIsMutable();
        coinPrices_.add(index, builderForValue.build());
        onChanged();
      } else {
        coinPricesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
     */
    public Builder addAllCoinPrices(
        java.lang.Iterable<? extends com.tradeflux.grpc.CoinPrice> values) {
      if (coinPricesBuilder_ == null) {
        ensureCoinPricesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, coinPrices_);
        onChanged();
      } else {
        coinPricesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
     */
    public Builder clearCoinPrices() {
      if (coinPricesBuilder_ == null) {
        coinPrices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        coinPricesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
     */
    public Builder removeCoinPrices(int index) {
      if (coinPricesBuilder_ == null) {
        ensureCoinPricesIsMutable();
        coinPrices_.remove(index);
        onChanged();
      } else {
        coinPricesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
     */
    public com.tradeflux.grpc.CoinPrice.Builder getCoinPricesBuilder(
        int index) {
      return getCoinPricesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
     */
    public com.tradeflux.grpc.CoinPriceOrBuilder getCoinPricesOrBuilder(
        int index) {
      if (coinPricesBuilder_ == null) {
        return coinPrices_.get(index);  } else {
        return coinPricesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
     */
    public java.util.List<? extends com.tradeflux.grpc.CoinPriceOrBuilder> 
         getCoinPricesOrBuilderList() {
      if (coinPricesBuilder_ != null) {
        return coinPricesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(coinPrices_);
      }
    }
    /**
     * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
     */
    public com.tradeflux.grpc.CoinPrice.Builder addCoinPricesBuilder() {
      return getCoinPricesFieldBuilder().addBuilder(
          com.tradeflux.grpc.CoinPrice.getDefaultInstance());
    }
    /**
     * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
     */
    public com.tradeflux.grpc.CoinPrice.Builder addCoinPricesBuilder(
        int index) {
      return getCoinPricesFieldBuilder().addBuilder(
          index, com.tradeflux.grpc.CoinPrice.getDefaultInstance());
    }
    /**
     * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
     */
    public java.util.List<com.tradeflux.grpc.CoinPrice.Builder> 
         getCoinPricesBuilderList() {
      return getCoinPricesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tradeflux.grpc.CoinPrice, com.tradeflux.grpc.CoinPrice.Builder, com.tradeflux.grpc.CoinPriceOrBuilder> 
        getCoinPricesFieldBuilder() {
      if (coinPricesBuilder_ == null) {
        coinPricesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.tradeflux.grpc.CoinPrice, com.tradeflux.grpc.CoinPrice.Builder, com.tradeflux.grpc.CoinPriceOrBuilder>(
                coinPrices_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        coinPrices_ = null;
      }
      return coinPricesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tradeflux.PriceResponse)
  }

  // @@protoc_insertion_point(class_scope:tradeflux.PriceResponse)
  private static final com.tradeflux.grpc.PriceResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tradeflux.grpc.PriceResponse();
  }

  public static com.tradeflux.grpc.PriceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PriceResponse>
      PARSER = new com.google.protobuf.AbstractParser<PriceResponse>() {
    @java.lang.Override
    public PriceResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PriceResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PriceResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PriceResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tradeflux.grpc.PriceResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

