// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

public interface PriceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tradeflux.PriceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
   */
  java.util.List<com.tradeflux.grpc.CoinPrice> 
      getCoinPricesList();
  /**
   * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
   */
  com.tradeflux.grpc.CoinPrice getCoinPrices(int index);
  /**
   * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
   */
  int getCoinPricesCount();
  /**
   * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
   */
  java.util.List<? extends com.tradeflux.grpc.CoinPriceOrBuilder> 
      getCoinPricesOrBuilderList();
  /**
   * <code>repeated .tradeflux.CoinPrice coin_prices = 1;</code>
   */
  com.tradeflux.grpc.CoinPriceOrBuilder getCoinPricesOrBuilder(
      int index);
}
