// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

/**
 * Protobuf enum {@code tradeflux.RateLimitInterval}
 */
public enum RateLimitInterval
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>RATE_LIMIT_UNKNOWN = 0;</code>
   */
  RATE_LIMIT_UNKNOWN(0),
  /**
   * <code>SECOND = 1;</code>
   */
  SECOND(1),
  /**
   * <code>MINUTE = 2;</code>
   */
  MINUTE(2),
  /**
   * <code>DAY = 3;</code>
   */
  DAY(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>RATE_LIMIT_UNKNOWN = 0;</code>
   */
  public static final int RATE_LIMIT_UNKNOWN_VALUE = 0;
  /**
   * <code>SECOND = 1;</code>
   */
  public static final int SECOND_VALUE = 1;
  /**
   * <code>MINUTE = 2;</code>
   */
  public static final int MINUTE_VALUE = 2;
  /**
   * <code>DAY = 3;</code>
   */
  public static final int DAY_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RateLimitInterval valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static RateLimitInterval forNumber(int value) {
    switch (value) {
      case 0: return RATE_LIMIT_UNKNOWN;
      case 1: return SECOND;
      case 2: return MINUTE;
      case 3: return DAY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RateLimitInterval>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RateLimitInterval> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RateLimitInterval>() {
          public RateLimitInterval findValueByNumber(int number) {
            return RateLimitInterval.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.tradeflux.grpc.Tradeflux.getDescriptor().getEnumTypes().get(1);
  }

  private static final RateLimitInterval[] VALUES = values();

  public static RateLimitInterval valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RateLimitInterval(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:tradeflux.RateLimitInterval)
}

