// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

public interface StreamNBBOResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tradeflux.StreamNBBOResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
   */
  java.util.List<com.tradeflux.grpc.NBBO> 
      getNbboListList();
  /**
   * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
   */
  com.tradeflux.grpc.NBBO getNbboList(int index);
  /**
   * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
   */
  int getNbboListCount();
  /**
   * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
   */
  java.util.List<? extends com.tradeflux.grpc.NBBOOrBuilder> 
      getNbboListOrBuilderList();
  /**
   * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
   */
  com.tradeflux.grpc.NBBOOrBuilder getNbboListOrBuilder(
      int index);
}
