// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

public interface StreamNBBOResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tradeflux.StreamNBBOResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tradeflux.NBBO nbbo = 1;</code>
   * @return Whether the nbbo field is set.
   */
  boolean hasNbbo();
  /**
   * <code>.tradeflux.NBBO nbbo = 1;</code>
   * @return The nbbo.
   */
  com.tradeflux.grpc.NBBO getNbbo();
  /**
   * <code>.tradeflux.NBBO nbbo = 1;</code>
   */
  com.tradeflux.grpc.NBBOOrBuilder getNbboOrBuilder();
}
