// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

/**
 * Protobuf type {@code tradeflux.StreamNBBOResponse}
 */
public final class StreamNBBOResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tradeflux.StreamNBBOResponse)
    StreamNBBOResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamNBBOResponse.newBuilder() to construct.
  private StreamNBBOResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamNBBOResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StreamNBBOResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StreamNBBOResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.tradeflux.grpc.NBBO.Builder subBuilder = null;
            if (nbbo_ != null) {
              subBuilder = nbbo_.toBuilder();
            }
            nbbo_ = input.readMessage(com.tradeflux.grpc.NBBO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(nbbo_);
              nbbo_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_StreamNBBOResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_StreamNBBOResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tradeflux.grpc.StreamNBBOResponse.class, com.tradeflux.grpc.StreamNBBOResponse.Builder.class);
  }

  public static final int NBBO_FIELD_NUMBER = 1;
  private com.tradeflux.grpc.NBBO nbbo_;
  /**
   * <code>.tradeflux.NBBO nbbo = 1;</code>
   * @return Whether the nbbo field is set.
   */
  @java.lang.Override
  public boolean hasNbbo() {
    return nbbo_ != null;
  }
  /**
   * <code>.tradeflux.NBBO nbbo = 1;</code>
   * @return The nbbo.
   */
  @java.lang.Override
  public com.tradeflux.grpc.NBBO getNbbo() {
    return nbbo_ == null ? com.tradeflux.grpc.NBBO.getDefaultInstance() : nbbo_;
  }
  /**
   * <code>.tradeflux.NBBO nbbo = 1;</code>
   */
  @java.lang.Override
  public com.tradeflux.grpc.NBBOOrBuilder getNbboOrBuilder() {
    return getNbbo();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (nbbo_ != null) {
      output.writeMessage(1, getNbbo());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (nbbo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getNbbo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tradeflux.grpc.StreamNBBOResponse)) {
      return super.equals(obj);
    }
    com.tradeflux.grpc.StreamNBBOResponse other = (com.tradeflux.grpc.StreamNBBOResponse) obj;

    if (hasNbbo() != other.hasNbbo()) return false;
    if (hasNbbo()) {
      if (!getNbbo()
          .equals(other.getNbbo())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasNbbo()) {
      hash = (37 * hash) + NBBO_FIELD_NUMBER;
      hash = (53 * hash) + getNbbo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tradeflux.grpc.StreamNBBOResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tradeflux.grpc.StreamNBBOResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tradeflux.StreamNBBOResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tradeflux.StreamNBBOResponse)
      com.tradeflux.grpc.StreamNBBOResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_StreamNBBOResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_StreamNBBOResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tradeflux.grpc.StreamNBBOResponse.class, com.tradeflux.grpc.StreamNBBOResponse.Builder.class);
    }

    // Construct using com.tradeflux.grpc.StreamNBBOResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (nbboBuilder_ == null) {
        nbbo_ = null;
      } else {
        nbbo_ = null;
        nbboBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_StreamNBBOResponse_descriptor;
    }

    @java.lang.Override
    public com.tradeflux.grpc.StreamNBBOResponse getDefaultInstanceForType() {
      return com.tradeflux.grpc.StreamNBBOResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.tradeflux.grpc.StreamNBBOResponse build() {
      com.tradeflux.grpc.StreamNBBOResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tradeflux.grpc.StreamNBBOResponse buildPartial() {
      com.tradeflux.grpc.StreamNBBOResponse result = new com.tradeflux.grpc.StreamNBBOResponse(this);
      if (nbboBuilder_ == null) {
        result.nbbo_ = nbbo_;
      } else {
        result.nbbo_ = nbboBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tradeflux.grpc.StreamNBBOResponse) {
        return mergeFrom((com.tradeflux.grpc.StreamNBBOResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tradeflux.grpc.StreamNBBOResponse other) {
      if (other == com.tradeflux.grpc.StreamNBBOResponse.getDefaultInstance()) return this;
      if (other.hasNbbo()) {
        mergeNbbo(other.getNbbo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tradeflux.grpc.StreamNBBOResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tradeflux.grpc.StreamNBBOResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.tradeflux.grpc.NBBO nbbo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tradeflux.grpc.NBBO, com.tradeflux.grpc.NBBO.Builder, com.tradeflux.grpc.NBBOOrBuilder> nbboBuilder_;
    /**
     * <code>.tradeflux.NBBO nbbo = 1;</code>
     * @return Whether the nbbo field is set.
     */
    public boolean hasNbbo() {
      return nbboBuilder_ != null || nbbo_ != null;
    }
    /**
     * <code>.tradeflux.NBBO nbbo = 1;</code>
     * @return The nbbo.
     */
    public com.tradeflux.grpc.NBBO getNbbo() {
      if (nbboBuilder_ == null) {
        return nbbo_ == null ? com.tradeflux.grpc.NBBO.getDefaultInstance() : nbbo_;
      } else {
        return nbboBuilder_.getMessage();
      }
    }
    /**
     * <code>.tradeflux.NBBO nbbo = 1;</code>
     */
    public Builder setNbbo(com.tradeflux.grpc.NBBO value) {
      if (nbboBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nbbo_ = value;
        onChanged();
      } else {
        nbboBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.tradeflux.NBBO nbbo = 1;</code>
     */
    public Builder setNbbo(
        com.tradeflux.grpc.NBBO.Builder builderForValue) {
      if (nbboBuilder_ == null) {
        nbbo_ = builderForValue.build();
        onChanged();
      } else {
        nbboBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.tradeflux.NBBO nbbo = 1;</code>
     */
    public Builder mergeNbbo(com.tradeflux.grpc.NBBO value) {
      if (nbboBuilder_ == null) {
        if (nbbo_ != null) {
          nbbo_ =
            com.tradeflux.grpc.NBBO.newBuilder(nbbo_).mergeFrom(value).buildPartial();
        } else {
          nbbo_ = value;
        }
        onChanged();
      } else {
        nbboBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.tradeflux.NBBO nbbo = 1;</code>
     */
    public Builder clearNbbo() {
      if (nbboBuilder_ == null) {
        nbbo_ = null;
        onChanged();
      } else {
        nbbo_ = null;
        nbboBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.tradeflux.NBBO nbbo = 1;</code>
     */
    public com.tradeflux.grpc.NBBO.Builder getNbboBuilder() {
      
      onChanged();
      return getNbboFieldBuilder().getBuilder();
    }
    /**
     * <code>.tradeflux.NBBO nbbo = 1;</code>
     */
    public com.tradeflux.grpc.NBBOOrBuilder getNbboOrBuilder() {
      if (nbboBuilder_ != null) {
        return nbboBuilder_.getMessageOrBuilder();
      } else {
        return nbbo_ == null ?
            com.tradeflux.grpc.NBBO.getDefaultInstance() : nbbo_;
      }
    }
    /**
     * <code>.tradeflux.NBBO nbbo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tradeflux.grpc.NBBO, com.tradeflux.grpc.NBBO.Builder, com.tradeflux.grpc.NBBOOrBuilder> 
        getNbboFieldBuilder() {
      if (nbboBuilder_ == null) {
        nbboBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tradeflux.grpc.NBBO, com.tradeflux.grpc.NBBO.Builder, com.tradeflux.grpc.NBBOOrBuilder>(
                getNbbo(),
                getParentForChildren(),
                isClean());
        nbbo_ = null;
      }
      return nbboBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tradeflux.StreamNBBOResponse)
  }

  // @@protoc_insertion_point(class_scope:tradeflux.StreamNBBOResponse)
  private static final com.tradeflux.grpc.StreamNBBOResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tradeflux.grpc.StreamNBBOResponse();
  }

  public static com.tradeflux.grpc.StreamNBBOResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamNBBOResponse>
      PARSER = new com.google.protobuf.AbstractParser<StreamNBBOResponse>() {
    @java.lang.Override
    public StreamNBBOResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StreamNBBOResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StreamNBBOResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamNBBOResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tradeflux.grpc.StreamNBBOResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

