// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

/**
 * Protobuf type {@code tradeflux.StreamNBBOResponse}
 */
public final class StreamNBBOResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tradeflux.StreamNBBOResponse)
    StreamNBBOResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamNBBOResponse.newBuilder() to construct.
  private StreamNBBOResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamNBBOResponse() {
    nbboList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StreamNBBOResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StreamNBBOResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              nbboList_ = new java.util.ArrayList<com.tradeflux.grpc.NBBO>();
              mutable_bitField0_ |= 0x00000001;
            }
            nbboList_.add(
                input.readMessage(com.tradeflux.grpc.NBBO.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        nbboList_ = java.util.Collections.unmodifiableList(nbboList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_StreamNBBOResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_StreamNBBOResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tradeflux.grpc.StreamNBBOResponse.class, com.tradeflux.grpc.StreamNBBOResponse.Builder.class);
  }

  public static final int NBBO_LIST_FIELD_NUMBER = 1;
  private java.util.List<com.tradeflux.grpc.NBBO> nbboList_;
  /**
   * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.tradeflux.grpc.NBBO> getNbboListList() {
    return nbboList_;
  }
  /**
   * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.tradeflux.grpc.NBBOOrBuilder> 
      getNbboListOrBuilderList() {
    return nbboList_;
  }
  /**
   * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
   */
  @java.lang.Override
  public int getNbboListCount() {
    return nbboList_.size();
  }
  /**
   * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
   */
  @java.lang.Override
  public com.tradeflux.grpc.NBBO getNbboList(int index) {
    return nbboList_.get(index);
  }
  /**
   * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
   */
  @java.lang.Override
  public com.tradeflux.grpc.NBBOOrBuilder getNbboListOrBuilder(
      int index) {
    return nbboList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < nbboList_.size(); i++) {
      output.writeMessage(1, nbboList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < nbboList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, nbboList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tradeflux.grpc.StreamNBBOResponse)) {
      return super.equals(obj);
    }
    com.tradeflux.grpc.StreamNBBOResponse other = (com.tradeflux.grpc.StreamNBBOResponse) obj;

    if (!getNbboListList()
        .equals(other.getNbboListList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getNbboListCount() > 0) {
      hash = (37 * hash) + NBBO_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getNbboListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tradeflux.grpc.StreamNBBOResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tradeflux.grpc.StreamNBBOResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tradeflux.grpc.StreamNBBOResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tradeflux.StreamNBBOResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tradeflux.StreamNBBOResponse)
      com.tradeflux.grpc.StreamNBBOResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_StreamNBBOResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_StreamNBBOResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tradeflux.grpc.StreamNBBOResponse.class, com.tradeflux.grpc.StreamNBBOResponse.Builder.class);
    }

    // Construct using com.tradeflux.grpc.StreamNBBOResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getNbboListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (nbboListBuilder_ == null) {
        nbboList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        nbboListBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tradeflux.grpc.Tradeflux.internal_static_tradeflux_StreamNBBOResponse_descriptor;
    }

    @java.lang.Override
    public com.tradeflux.grpc.StreamNBBOResponse getDefaultInstanceForType() {
      return com.tradeflux.grpc.StreamNBBOResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.tradeflux.grpc.StreamNBBOResponse build() {
      com.tradeflux.grpc.StreamNBBOResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tradeflux.grpc.StreamNBBOResponse buildPartial() {
      com.tradeflux.grpc.StreamNBBOResponse result = new com.tradeflux.grpc.StreamNBBOResponse(this);
      int from_bitField0_ = bitField0_;
      if (nbboListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          nbboList_ = java.util.Collections.unmodifiableList(nbboList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.nbboList_ = nbboList_;
      } else {
        result.nbboList_ = nbboListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tradeflux.grpc.StreamNBBOResponse) {
        return mergeFrom((com.tradeflux.grpc.StreamNBBOResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tradeflux.grpc.StreamNBBOResponse other) {
      if (other == com.tradeflux.grpc.StreamNBBOResponse.getDefaultInstance()) return this;
      if (nbboListBuilder_ == null) {
        if (!other.nbboList_.isEmpty()) {
          if (nbboList_.isEmpty()) {
            nbboList_ = other.nbboList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNbboListIsMutable();
            nbboList_.addAll(other.nbboList_);
          }
          onChanged();
        }
      } else {
        if (!other.nbboList_.isEmpty()) {
          if (nbboListBuilder_.isEmpty()) {
            nbboListBuilder_.dispose();
            nbboListBuilder_ = null;
            nbboList_ = other.nbboList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            nbboListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNbboListFieldBuilder() : null;
          } else {
            nbboListBuilder_.addAllMessages(other.nbboList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tradeflux.grpc.StreamNBBOResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tradeflux.grpc.StreamNBBOResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.tradeflux.grpc.NBBO> nbboList_ =
      java.util.Collections.emptyList();
    private void ensureNbboListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        nbboList_ = new java.util.ArrayList<com.tradeflux.grpc.NBBO>(nbboList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tradeflux.grpc.NBBO, com.tradeflux.grpc.NBBO.Builder, com.tradeflux.grpc.NBBOOrBuilder> nbboListBuilder_;

    /**
     * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
     */
    public java.util.List<com.tradeflux.grpc.NBBO> getNbboListList() {
      if (nbboListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(nbboList_);
      } else {
        return nbboListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
     */
    public int getNbboListCount() {
      if (nbboListBuilder_ == null) {
        return nbboList_.size();
      } else {
        return nbboListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
     */
    public com.tradeflux.grpc.NBBO getNbboList(int index) {
      if (nbboListBuilder_ == null) {
        return nbboList_.get(index);
      } else {
        return nbboListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
     */
    public Builder setNbboList(
        int index, com.tradeflux.grpc.NBBO value) {
      if (nbboListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNbboListIsMutable();
        nbboList_.set(index, value);
        onChanged();
      } else {
        nbboListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
     */
    public Builder setNbboList(
        int index, com.tradeflux.grpc.NBBO.Builder builderForValue) {
      if (nbboListBuilder_ == null) {
        ensureNbboListIsMutable();
        nbboList_.set(index, builderForValue.build());
        onChanged();
      } else {
        nbboListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
     */
    public Builder addNbboList(com.tradeflux.grpc.NBBO value) {
      if (nbboListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNbboListIsMutable();
        nbboList_.add(value);
        onChanged();
      } else {
        nbboListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
     */
    public Builder addNbboList(
        int index, com.tradeflux.grpc.NBBO value) {
      if (nbboListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNbboListIsMutable();
        nbboList_.add(index, value);
        onChanged();
      } else {
        nbboListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
     */
    public Builder addNbboList(
        com.tradeflux.grpc.NBBO.Builder builderForValue) {
      if (nbboListBuilder_ == null) {
        ensureNbboListIsMutable();
        nbboList_.add(builderForValue.build());
        onChanged();
      } else {
        nbboListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
     */
    public Builder addNbboList(
        int index, com.tradeflux.grpc.NBBO.Builder builderForValue) {
      if (nbboListBuilder_ == null) {
        ensureNbboListIsMutable();
        nbboList_.add(index, builderForValue.build());
        onChanged();
      } else {
        nbboListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
     */
    public Builder addAllNbboList(
        java.lang.Iterable<? extends com.tradeflux.grpc.NBBO> values) {
      if (nbboListBuilder_ == null) {
        ensureNbboListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, nbboList_);
        onChanged();
      } else {
        nbboListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
     */
    public Builder clearNbboList() {
      if (nbboListBuilder_ == null) {
        nbboList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        nbboListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
     */
    public Builder removeNbboList(int index) {
      if (nbboListBuilder_ == null) {
        ensureNbboListIsMutable();
        nbboList_.remove(index);
        onChanged();
      } else {
        nbboListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
     */
    public com.tradeflux.grpc.NBBO.Builder getNbboListBuilder(
        int index) {
      return getNbboListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
     */
    public com.tradeflux.grpc.NBBOOrBuilder getNbboListOrBuilder(
        int index) {
      if (nbboListBuilder_ == null) {
        return nbboList_.get(index);  } else {
        return nbboListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
     */
    public java.util.List<? extends com.tradeflux.grpc.NBBOOrBuilder> 
         getNbboListOrBuilderList() {
      if (nbboListBuilder_ != null) {
        return nbboListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(nbboList_);
      }
    }
    /**
     * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
     */
    public com.tradeflux.grpc.NBBO.Builder addNbboListBuilder() {
      return getNbboListFieldBuilder().addBuilder(
          com.tradeflux.grpc.NBBO.getDefaultInstance());
    }
    /**
     * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
     */
    public com.tradeflux.grpc.NBBO.Builder addNbboListBuilder(
        int index) {
      return getNbboListFieldBuilder().addBuilder(
          index, com.tradeflux.grpc.NBBO.getDefaultInstance());
    }
    /**
     * <code>repeated .tradeflux.NBBO nbbo_list = 1;</code>
     */
    public java.util.List<com.tradeflux.grpc.NBBO.Builder> 
         getNbboListBuilderList() {
      return getNbboListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tradeflux.grpc.NBBO, com.tradeflux.grpc.NBBO.Builder, com.tradeflux.grpc.NBBOOrBuilder> 
        getNbboListFieldBuilder() {
      if (nbboListBuilder_ == null) {
        nbboListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.tradeflux.grpc.NBBO, com.tradeflux.grpc.NBBO.Builder, com.tradeflux.grpc.NBBOOrBuilder>(
                nbboList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        nbboList_ = null;
      }
      return nbboListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tradeflux.StreamNBBOResponse)
  }

  // @@protoc_insertion_point(class_scope:tradeflux.StreamNBBOResponse)
  private static final com.tradeflux.grpc.StreamNBBOResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tradeflux.grpc.StreamNBBOResponse();
  }

  public static com.tradeflux.grpc.StreamNBBOResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamNBBOResponse>
      PARSER = new com.google.protobuf.AbstractParser<StreamNBBOResponse>() {
    @java.lang.Override
    public StreamNBBOResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StreamNBBOResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StreamNBBOResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamNBBOResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tradeflux.grpc.StreamNBBOResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

