// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/tradeflux.proto

package com.tradeflux.grpc;

public final class Tradeflux {
  private Tradeflux() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflux_EmptyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflux_EmptyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflux_CoinInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflux_CoinInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflux_CoinListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflux_CoinListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflux_CoinRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflux_CoinRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflux_CoinPrice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflux_CoinPrice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflux_PriceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflux_PriceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflux_HistoricalOHLCRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflux_HistoricalOHLCRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflux_OHLCData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflux_OHLCData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflux_HistoricalOHLCResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflux_HistoricalOHLCResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflux_OHLCDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflux_OHLCDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflux_NBBO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflux_NBBO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tradeflux_StreamNBBOResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tradeflux_StreamNBBOResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024grpc/tradeflux.proto\022\ttradeflux\"\016\n\014Emp" +
      "tyRequest\"\222\001\n\010CoinInfo\022\016\n\006symbol\030\001 \001(\t\022\022" +
      "\n\nbase_asset\030\002 \001(\t\022\023\n\013quote_asset\030\003 \001(\t\022" +
      "*\n\013order_types\030\004 \003(\0162\025.tradeflux.OrderTy" +
      "pes\022!\n\031is_margin_trading_allowed\030\005 \001(\010\"6" +
      "\n\020CoinListResponse\022\"\n\005coins\030\001 \003(\0132\023.trad" +
      "eflux.CoinInfo\"\036\n\013CoinRequest\022\017\n\007symbols" +
      "\030\001 \003(\t\"\316\001\n\tCoinPrice\022\016\n\006symbol\030\001 \001(\t\022\r\n\005" +
      "price\030\002 \001(\001\022(\n\033average_price_interval_mi" +
      "ns\030\003 \001(\005H\000\210\001\001\022\034\n\017last_trade_time\030\004 \001(\003H\001" +
      "\210\001\001\022\027\n\nevent_time\030\005 \001(\003H\002\210\001\001B\036\n\034_average" +
      "_price_interval_minsB\022\n\020_last_trade_time" +
      "B\r\n\013_event_time\":\n\rPriceResponse\022)\n\013coin" +
      "_prices\030\001 \003(\0132\024.tradeflux.CoinPrice\"\334\001\n\025" +
      "HistoricalOHLCRequest\022\016\n\006symbol\030\001 \001(\t\022%\n" +
      "\010interval\030\002 \001(\0162\023.tradeflux.Interval\022\027\n\n" +
      "start_time\030\003 \001(\003H\000\210\001\001\022\025\n\010end_time\030\004 \001(\003H" +
      "\001\210\001\001\022\025\n\010timezone\030\005 \001(\tH\002\210\001\001\022\022\n\005limit\030\006 \001" +
      "(\005H\003\210\001\001B\r\n\013_start_timeB\013\n\t_end_timeB\013\n\t_" +
      "timezoneB\010\n\006_limit\"\376\001\n\010OHLCData\022\027\n\017kline" +
      "_open_time\030\001 \001(\003\022\022\n\nopen_price\030\002 \001(\001\022\022\n\n" +
      "high_price\030\003 \001(\001\022\021\n\tlow_price\030\004 \001(\001\022\016\n\006v" +
      "olume\030\005 \001(\001\022\030\n\020kline_close_time\030\006 \001(\003\022\032\n" +
      "\022quote_asset_volume\030\007 \001(\001\022\030\n\020number_of_t" +
      "rades\030\010 \001(\003\022\033\n\023taker_buy_asset_vol\030\t \001(\001" +
      "\022!\n\031taker_buy_quote_asset_vol\030\n \001(\001\"@\n\026H" +
      "istoricalOHLCResponse\022&\n\tOHLC_data\030\001 \003(\013" +
      "2\023.tradeflux.OHLCData\"Z\n\020OHLCDataRespons" +
      "e\022\016\n\006symbol\030\001 \001(\t\022\020\n\010interval\030\002 \001(\t\022$\n\007c" +
      "andles\030\003 \003(\0132\023.tradeflux.OHLCData\"h\n\004NBB" +
      "O\022\016\n\006symbol\030\001 \001(\t\022\021\n\tbid_price\030\002 \001(\001\022\024\n\014" +
      "bid_quantity\030\003 \001(\001\022\021\n\task_price\030\004 \001(\001\022\024\n" +
      "\014ask_quantity\030\005 \001(\001\"8\n\022StreamNBBORespons" +
      "e\022\"\n\tnbbo_list\030\001 \003(\0132\017.tradeflux.NBBO*\353\001" +
      "\n\010Interval\022\024\n\020INTERVAL_UNKNOWN\020\000\022\t\n\005SEC_" +
      "1\020\001\022\014\n\010MINUTE_1\020\002\022\014\n\010MINUTE_3\020\003\022\014\n\010MINUT" +
      "E_5\020\004\022\r\n\tMINUTE_15\020\005\022\r\n\tMINUTE_30\020\006\022\n\n\006H" +
      "OUR_1\020\007\022\n\n\006HOUR_2\020\010\022\n\n\006HOUR_4\020\t\022\n\n\006HOUR_" +
      "6\020\n\022\n\n\006HOUR_8\020\013\022\013\n\007HOUR_12\020\014\022\t\n\005DAY_1\020\r\022" +
      "\t\n\005DAY_3\020\016\022\n\n\006WEEK_1\020\017\022\013\n\007MONTH_1\020\020*L\n\021R" +
      "ateLimitInterval\022\026\n\022RATE_LIMIT_UNKNOWN\020\000" +
      "\022\n\n\006SECOND\020\001\022\n\n\006MINUTE\020\002\022\007\n\003DAY\020\003*\230\001\n\nOr" +
      "derTypes\022\026\n\022ORDER_TYPE_UNKNOWN\020\000\022\t\n\005LIMI" +
      "T\020\001\022\n\n\006MARKET\020\002\022\r\n\tSTOP_LOSS\020\003\022\023\n\017STOP_L" +
      "OSS_LIMIT\020\004\022\017\n\013TAKE_PROFIT\020\005\022\025\n\021TAKE_PRO" +
      "FIT_LIMIT\020\006\022\017\n\013LIMIT_MAKER\020\0072\226\003\n\021MarketD" +
      "ataService\022K\n\021GetAvailableCoins\022\027.tradef" +
      "lux.EmptyRequest\032\033.tradeflux.CoinListRes" +
      "ponse\"\000\022E\n\017GetCurrentPrice\022\026.tradeflux.C" +
      "oinRequest\032\030.tradeflux.PriceResponse\"\000\022^" +
      "\n\025GetHistoricalOHLCData\022 .tradeflux.Hist" +
      "oricalOHLCRequest\032!.tradeflux.Historical" +
      "OHLCResponse\"\000\022F\n\016StreamAvgPrice\022\026.trade" +
      "flux.CoinRequest\032\030.tradeflux.PriceRespon" +
      "se\"\0000\001\022E\n\nStreamNBBO\022\026.tradeflux.CoinReq" +
      "uest\032\035.tradeflux.StreamNBBOResponse\"\000B\026\n" +
      "\022com.tradeflux.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tradeflux_EmptyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tradeflux_EmptyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflux_EmptyRequest_descriptor,
        new java.lang.String[] { });
    internal_static_tradeflux_CoinInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tradeflux_CoinInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflux_CoinInfo_descriptor,
        new java.lang.String[] { "Symbol", "BaseAsset", "QuoteAsset", "OrderTypes", "IsMarginTradingAllowed", });
    internal_static_tradeflux_CoinListResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tradeflux_CoinListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflux_CoinListResponse_descriptor,
        new java.lang.String[] { "Coins", });
    internal_static_tradeflux_CoinRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tradeflux_CoinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflux_CoinRequest_descriptor,
        new java.lang.String[] { "Symbols", });
    internal_static_tradeflux_CoinPrice_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tradeflux_CoinPrice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflux_CoinPrice_descriptor,
        new java.lang.String[] { "Symbol", "Price", "AveragePriceIntervalMins", "LastTradeTime", "EventTime", "AveragePriceIntervalMins", "LastTradeTime", "EventTime", });
    internal_static_tradeflux_PriceResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_tradeflux_PriceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflux_PriceResponse_descriptor,
        new java.lang.String[] { "CoinPrices", });
    internal_static_tradeflux_HistoricalOHLCRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_tradeflux_HistoricalOHLCRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflux_HistoricalOHLCRequest_descriptor,
        new java.lang.String[] { "Symbol", "Interval", "StartTime", "EndTime", "Timezone", "Limit", "StartTime", "EndTime", "Timezone", "Limit", });
    internal_static_tradeflux_OHLCData_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_tradeflux_OHLCData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflux_OHLCData_descriptor,
        new java.lang.String[] { "KlineOpenTime", "OpenPrice", "HighPrice", "LowPrice", "Volume", "KlineCloseTime", "QuoteAssetVolume", "NumberOfTrades", "TakerBuyAssetVol", "TakerBuyQuoteAssetVol", });
    internal_static_tradeflux_HistoricalOHLCResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_tradeflux_HistoricalOHLCResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflux_HistoricalOHLCResponse_descriptor,
        new java.lang.String[] { "OHLCData", });
    internal_static_tradeflux_OHLCDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_tradeflux_OHLCDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflux_OHLCDataResponse_descriptor,
        new java.lang.String[] { "Symbol", "Interval", "Candles", });
    internal_static_tradeflux_NBBO_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_tradeflux_NBBO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflux_NBBO_descriptor,
        new java.lang.String[] { "Symbol", "BidPrice", "BidQuantity", "AskPrice", "AskQuantity", });
    internal_static_tradeflux_StreamNBBOResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_tradeflux_StreamNBBOResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tradeflux_StreamNBBOResponse_descriptor,
        new java.lang.String[] { "NbboList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
